### PR TITLE
LPS-93619 SF

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72815. [See changes here.](https://github.com/ealonso/liferay-portal/compare/1c73611f6a1c~3...1c73611f6a1c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
