### PR TITLE
LPS-77721 Contextual sidebar navigation menus

### PR DESCRIPTION
**Pull request by p2kmgcl**
/cc @jbalsas

### CODE REVIEW

**Comment by p2kmgcl** [comment]
@jbalsas por mi bien :man_shrugging:

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55623. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55624. [See changes here.](https://github.com/ealonso/liferay-portal/compare/3001ebe53674~2...3001ebe53674) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
