### PR TITLE
LPS-107678 Update styles for master layout

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
el ultimo commit @JuanAntol

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83919. [See changes here.](https://github.com/ealonso/liferay-portal/compare/f245ddd93d77~1...f245ddd93d77) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
