### PR TITLE
LPS-107565 Show content performance panel only for JournalArticle and BlogEntry

### PR DESCRIPTION
**Pull request by darquesdev**
@dgarciasarai @andresfulla

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83913. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
