### PR TITLE
LPS-77244 Buildlang

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by psavinov** [comment]
ci:test

**Comment by pavel-savinov** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56132. [See changes here.](https://github.com/ealonso/liferay-portal/compare/f9b6e34db192~8...f9b6e34db192) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
