### PR TITLE
LPS-106619 Create initial Content Performance panel

### PR DESCRIPTION
**Pull request by darquesdev**
@dgarciasarai

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83545. [See changes here.](https://github.com/ealonso/liferay-portal/compare/6d3ca20c5422~7...6d3ca20c5422) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83546. [See changes here.](https://github.com/ealonso/liferay-portal/compare/a408c34a0fd2~7...a408c34a0fd2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83567. [See changes here.](https://github.com/ealonso/liferay-portal/compare/e2d263f06c9c~1...e2d263f06c9c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83568. [See changes here.](https://github.com/ealonso/liferay-portal/compare/6f4e70c9c0e3~1...6f4e70c9c0e3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83570. [See changes here.](https://github.com/ealonso/liferay-portal/compare/64db9e6e7d63~1...64db9e6e7d63) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
