### PR TITLE
LPS-79455 Show alert and avoid publishing fragment entry with invalid HTML content

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
@p2kmgcl Could you please take a look at two last commits?

**Comment by pavel-savinov** [comment]
ci:test

**Comment by p2kmgcl** [comment]
:+1:
es bien

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56972. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
