### PR TITLE
LPS-71451 Fix staging publication for asset tags

### PR DESCRIPTION
**Pull request by matethurzo**
Hey @ealonso,

This change is fixing a bug in the asset tag publication, by introducing a bypass option called merge tags by name.

I've done some additional changes, can you please check if this is okay with you?

Thanks,

Máté

### CODE REVIEW

**Comment by matethurzo** [comment]
@ealonso fixed SF problems

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @matethurzo @akosthurzo,

There seems to be a rebase conflict, Could you please update the pull?

Regards,
Eudaldo.

**Comment by matethurzo** [comment]
@ealonso @akosthurzo rebased and pushed again

**Comment by ealonso** [comment]
@matethurzo @akosthurzo, thanks you very much guys!!

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53090. [See changes here.](https://github.com/ealonso/liferay-portal/compare/d7283ef~3...d7283ef) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53093. [See changes here.](https://github.com/ealonso/liferay-portal/compare/3a232b4~3...3a232b4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53104. [See changes here.](https://github.com/ealonso/liferay-portal/compare/947c13c~3...947c13c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53132. [See changes here.](https://github.com/ealonso/liferay-portal/compare/bb3c7f6~3...bb3c7f6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
