### PR TITLE
LPS-82801 We should not pass to the url the previous keywords parameter for the search URL. It will result in a duplication that could break the logic, since in this form the keyword parameter should be send using the input.

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
cc/ @dacousalr

**Comment by robertoDiaz** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60701. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
