### PR TITLE
[TECHNICAL-SUPPORT] LPS-79241

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @brianikim

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56697. [See changes here.](https://github.com/ealonso/liferay-portal/compare/ec1af6df5fad~1...ec1af6df5fad) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
