### PR TITLE
Lps 90642 experiences

### PR DESCRIPTION
**Pull request by andresfulla**
Some commits are not related to this pull. Hopefully they'll be in master tomorrow.
https://github.com/brianchandotcom/liferay-portal/pull/68680
@epgarcia @darquesdev

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
@andresfulla Can you have a look to the test error? Thx!

**Comment by andresfulla** [comment]
ci:retest

**Comment by andresfulla** [comment]
ci:test:relevant

**Comment by andresfulla** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:test:msb

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
@andresfulla please close this one. See #ealonso/liferay-portal/pull/2208

**Pull request closed without merging**
