### PR TITLE
LPS-104110 get article values and pass the them to taglib

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:test:sf

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83928. [See changes here.](https://github.com/ealonso/liferay-portal/compare/6f5a2bd09d01~2...6f5a2bd09d01) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83932. [See changes here.](https://github.com/ealonso/liferay-portal/compare/fb7a6dd64422~2...fb7a6dd64422) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
