### PR TITLE
LPS-84119

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@ealonso this causes compile issue since var `selected` does not exist.
Can you fix and send to Brian?

Thanks!

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78882. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by hhuijser** [comment]
Hey @ealonso, the reason I sent this to you is because this file is bad.
Adding the `=` exposes that the logic does not make sense because there is no variable `selected` defined.
You can see here, that the pull is closed because of compile issue: https://github.com/brianchandotcom/liferay-portal/pull/78882

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78992. [See changes here.](https://github.com/ealonso/liferay-portal/compare/086be9ec5b62~3...086be9ec5b62) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @hhuijser,

I've saw the problem and I've fixed it here: https://github.com/brianchandotcom/liferay-portal/pull/78992. The problem was that I've fixed it 2 days ago but I've forgot send to Brian the pr, 🤦‍♂

Thanks for the reminder.

Regards,
Eudaldo.

**Pull request closed without merging**
