### PR TITLE
LPS-107487 Moves JS closer to where the trigger is generated to ensure JS is executed in the correct order

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/2117. [See changes here.](https://github.com/ealonso/liferay-portal/compare/7e3eaa1fe732~1...7e3eaa1fe732) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
