### PR TITLE
[TS] LPS-94755

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-94755

CC @jrao

This fix is important if a user manipulates the URL manually, a more descriptive error message will appear.  Let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72389. [See changes here.](https://github.com/ealonso/liferay-portal/compare/4af92b385e33~2...4af92b385e33) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
