### PR TITLE
[TECHNICAL-SUPPORT] LPS-74783

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @mbowerman

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:reopen

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @mbowerman,

We are trying to avoid using queries that access tables from another modules as you can see:
https://grow.liferay.com/people/DXP-+How+to+code+upgrade+process+and+backport+rules#section-DXP-+How+to+code+upgrade+process+and+backport+rules-Golden+rule

Is it an exception? Do you have some performance data before and after your changes?

Regards,
Eudaldo.

**Comment by mbowerman** [comment]
Hi @ealonso,

This query was already referencing the DLFileVersion table anyway before I modified it.

In my opinion, it is very safe to assume that a DLFileEntry table will exist with a fileEntryId primary key column. We have code in portal-impl that interacts with the DLFileEntry table, so we know that the DLFileEntry table has to exist for any Liferay database. And we never modify the names of our primary key columns, especially within a release.

In my testing, I saw that this method took over 2 minutes to complete before my changes, but it took less than half a second to complete after my changes. However, I was testing with a small amount of orphaned AssetEntries. We have a customer for whom this method is taking almost an hour. Most likely, it will only take them a matter of seconds after my changes.

**Comment by mbowerman** [comment]
Hey @ealonso,

I cleared the cache since we are modifying the AssetEntry with SQL directly, whereas before we were modifying it with the API (which clears the cache for those entries). Since this is a Verify process, I believe it is possible to run it via Gogo Shell after Liferay has already started up and is in use. Therefore, these AssetEntries that are getting deleted could potentially already be in the cache. So clearing the cache seems appropriate if this is the case, since the AssetEntries that are getting deleted would remain in the cache otherwise.

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51694. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
@mbowerman Thanks you very much for your details.

**Pull request closed without merging**
