### PR TITLE
LPS-107369 Remove unused Geolocalization module and submodules

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83521. [See changes here.](https://github.com/ealonso/liferay-portal/compare/0fff986fd22a~1...0fff986fd22a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83526. [See changes here.](https://github.com/ealonso/liferay-portal/compare/b6b8b176df4c~2...b6b8b176df4c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
