### PR TITLE
Lps 99485

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @knchau

Notes from Kim:
> https://issues.liferay.com/browse/LPS-99485
> 
> This is a straightforward issue where the language key is not defined in the module where it is used. I added the language key in journal module since this file where language key is used was copied from ddm module.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79505. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
