### PR TITLE
LPS-76374

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/53939

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53943. [See changes here.](https://github.com/ealonso/liferay-portal/compare/1a54014~3...1a54014) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54061. [See changes here.](https://github.com/ealonso/liferay-portal/compare/fb6f358~3...fb6f358) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
