### PR TITLE
LPS-76235 Semantic versioning

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by pavel-savinov** [comment]
cc @ahdezma

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55621. [See changes here.](https://github.com/ealonso/liferay-portal/compare/9e344670bc08~11...9e344670bc08) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55643. [See changes here.](https://github.com/ealonso/liferay-portal/compare/da0693006026~13...da0693006026) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55650. [See changes here.](https://github.com/ealonso/liferay-portal/compare/967266ff5e1c~14...967266ff5e1c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
