### PR TITLE
LPS-71262 Do not populate data key when there are no selected items

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
@ealonso I believe this is your component. Please redirect otherwise, thanks!

**Comment by stsquared99** [comment]
cc @drewbrokke

**Comment by sandrodw3** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sandrodw3** [comment]
Pull request sent here: https://github.com/brianchandotcom/liferay-portal/pull/62416

**Comment by sandrodw3** [comment]
ci:close

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
