### PR TITLE
LPS-97404 baseline

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/victorg1991/liferay-portal/pull/30. [See changes here.](https://github.com/ealonso/liferay-portal/compare/6c4992c6b278~1...6c4992c6b278) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
