### PR TITLE
LPS-85996 Use all ancestor groups to validate asset vocabularies

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @ealonso ,

In the original code, the validation only ran for the vocabularies of the current and the Global groups (and no parent groups between them in the hierarchy).

For this fix, I used the same method to load all relevant AssetVocabularies as in: https://github.com/liferay/liferay-portal/blob/65059440dfaf2b8b365a20f99e83e4cdb15478aa/modules/apps/asset/asset-taglib/src/main/java/com/liferay/asset/taglib/servlet/taglib/AssetCategoriesSelectorTag.java#L234

Please review my changes.

Thanks,
Vendel

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test

**Comment by dacousalr** [comment]
ci:test

**Comment by dacousalr** [comment]
ci:test

**Comment by dacousalr** [comment]
ci:reopen

**Comment by dacousalr** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/dacousalr/liferay-portal/pull/66. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
