### PR TITLE
LPS-103460 Don't show duplicate button in drop zone

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Source format is failling locally for files I didn't even edited, let's see what the ci says

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80050. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
