### PR TITLE
[TS] LPS-110168

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/dacousalr/liferay-portal/pull/204. [See changes here.](https://github.com/ealonso/liferay-portal/compare/34e8f8559a55~5...34e8f8559a55) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/dacousalr/liferay-portal/pull/205. [See changes here.](https://github.com/ealonso/liferay-portal/compare/84ce86d0f06f~6...84ce86d0f06f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
