### PR TITLE
master-qa-19774

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-19774

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32663. [See changes here.](https://github.com/ealonso/liferay-portal/compare/92c0fa4~1...92c0fa4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32670. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
