### PR TITLE
LPS-X Wip

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:echo

**Comment by ealonso** [comment]
ci:test:echo

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:echo

**Comment by ozysouza** [comment]
Hi @ealonso! The failures blocked [here](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1652474616&testrayRunId=1652474809) are not related to your changes but there's two other cases that maybe are.

The first I have finished the analysis and you can reproduce with these steps below:

1 - Add a site template
2 - Add a message boards widget to home page in the site template and publish
3 - Add a new site based on the site temlate
4 - Remove the view permissions in the message boards
5 - View the page as guest

Expected Result -> An error is thrown You do not have the roles required to access this portlet.
Actual Result -> The portlet is visible
Video: https://www.loom.com/share/6b9579743ba7461190823b37963f8546

I'm still veryfing the second test.

**Comment by Tim-Cao** [comment]
Thanks @ozysouza, you're right!

**Comment by ealonso** [comment]
ci:test:echo

**Comment by ozysouza** [comment]
@ealonso, now there's just the first issue about the message boards portlet without view permisson is visible to guest.

**Comment by ozysouza** [comment]
> @ozysouza What about the other ones? the upgrade processes

@ealonso, they're not related to your changes.

**Comment by ealonso** [comment]
ci:test:tango

**Comment by ealonso** [comment]
ci:test:echo

**Comment by ealonso** [comment]
ci:test:tango

**Comment by ealonso** [comment]
ci:test:echo

**Comment by ealonso** [comment]
ci:reevaluate:1377401_1441

**Comment by ealonso** [comment]
ci:test:echo

**Comment by ealonso** [comment]
ci:test:echo

**Comment by ozysouza** [comment]
Hi @ealonso! The failures above are not related to your changes :tada:

**Comment by ealonso** [comment]
Thanks you very much @ozysouza for your help!!

**Pull request closed without merging**
