### PR TITLE
LPS-86991 showAssetCount flag should not inhibit the calculation of the maxCount and minCount, thus the multiplier is not calculated either

### PR DESCRIPTION
**Pull request by rodrigopaulino**

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
sent here: https://github.com/brianchandotcom/liferay-portal/pull/64941

**Pull request closed without merging**
