### PR TITLE
LPS-106894 Create ExportLayoutPageTemplateEntriesMVCResourceCommand

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/ruben-pulido/liferay-portal/pull/160. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
