### PR TITLE
LPS-95848 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-95848

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:help

**Comment by kyle-miho** [comment]
ci:test:poshi

**Comment by kyle-miho** [comment]
@ealonso There is also an issue with being able to map display pages in this pull. I reproduced it locally as well. ResourceBundleUtil.getBundle seems to fail for some reason

https://testray.liferay.com/reports/production/logs/test-1-21/1558652320573/test-portal-acceptance-pullrequest%28master%29/4042/functional-tomcat90-mysql57-jdk8/34/0/LocalFile.DisplayPagesWithStagingAndWebContent_PublishDisplayPageMarkedAsDefault/index.html.gz

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73674. [See changes here.](https://github.com/ealonso/liferay-portal/compare/8723b55d11ed~5...8723b55d11ed) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
