### PR TITLE
LPS-78165 Individual updates

### PR DESCRIPTION
**Pull request by p2kmgcl**
/cc @jbalsas
/cc @jkappler

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test

**Comment by p2kmgcl** [comment]
@jkappler :c

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
Will fix and resend

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
please see: https://github.com/ealonso/liferay-portal/pull/1500

**Pull request closed without merging**
