### PR TITLE
LPS-85729 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-85729

### CODE REVIEW

**Comment by kyle-miho** [comment]
@ealonso Here are the necessary test fixes for the pull. Just remember Bchan's comment

> @ealonso can you deprecate changes that cause modules/apps/site-navigation/site-navigation-api/src/main/resources/com/liferay/site/navigation/constants/packageinfo to bump up? I saw them, and it wasn't that bad to deprecate.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63832. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63833. [See changes here.](https://github.com/ealonso/liferay-portal/compare/1d2a6158d01a~1...1d2a6158d01a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
