### PR TITLE
[TECHNICAL-SUPPORT] LPS-76648

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @mbowerman

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53920. [See changes here.](https://github.com/ealonso/liferay-portal/compare/af3563b~2...af3563b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
