### PR TITLE
LPS-110111 Enable collection items drag and drop

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/sandrodw3/liferay-portal/pull/259. [See changes here.](https://github.com/ealonso/liferay-portal/compare/efb01077e773~1...efb01077e773) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
