### PR TITLE
LPS-89622 SF

### PR DESCRIPTION
**Pull request by achaparro**
Hi @ealonso, @matethurzo,

When we publish articles to live we always create new FriendlyURLEntryLocalization records instead of updating current ones in Live. This is causing a lot of problem with duplicated friendlyURLs.

I have made some changes to reuse FriendlyURL records having just one record per resourcePrimKey in JournalArticle (with mutiple localizations).

Other possible solutions are:

- Use updateArticle (this method works well for staging) instead of addArticle when we publish a new version of an existing article.
- Since we publish friendlyURLs in two points (journal service and friendlyUrl staged handler), unifiy that logic.

Let me know if you have any question.

Thanks.

PS: I have also fixed issues comparing friendlyURLs (due wrong decode/encoding)

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
Hey @pavel-savinov,

I have added a missing commit, please take it into account.

Thanks.

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/67426

**Pull request closed without merging**
