### PR TITLE
LPS-75321

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LPS-75321

### CODE REVIEW

**Comment by anthony-chu** [comment]
hi @ealonso, thanks for all your hard work on this! i was able to fix the remaining CPPagetemplates test that was failing. however, i will still need to talk to the forms+workflow team to determine how to fix the tests in their subrepo. i'll try and let you know my findings as soon as i can.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/1226. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53018. [See changes here.](https://github.com/ealonso/liferay-portal/compare/3cc1e8b~3...3cc1e8b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
