### PR TITLE
dropzone-feedback-109717

### PR DESCRIPTION
**Pull request by p2kmgcl**
/cc @ealonso @veroglez @sandrodw3

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by jpince** [comment]
@p2kmgcl is there a reason you forwarded to Eudaldo? If ci:forward didn't work in the previous pull, that's feedback that the CII Team needs to know.

**Comment by ealonso** [comment]
Hey @jpince,
We are trying to know if it is a problem with Pablo’s github user or it is a general problem, since it is working for me today.

**Comment by ealonso** [comment]
ci:forward

**Comment by jpince** [comment]
@ealonso `ConvertBasicWidgetPageToContentPage` also failed in this PR https://github.com/p2kmgcl/liferay-portal/pull/598. Maybe time to quarantine before retesting?

cc/ @pavel-savinov

**Comment by jpince** [comment]
cc/ @david-gutierrez-mesa

**Comment by jpince** [comment]
@p2kmgcl I asked BChan to fetch the branch again, but he said he ran into the same rebase error

When I tried it myself, I was able to rebase, but the cherry-pick failed (and I think BChan cherry-picks).

```
[bchan-master 69bd3241af05] LPS-109717 Extract useDrag behaviour to useItemDragCreate new utils directory to group all generic stuff
 Author: Pablo Molina <contact@pablomolina.me>
 Date: Tue Mar 24 11:51:37 2020 +0100
 5 files changed, 112 insertions(+), 129 deletions(-)
 create mode 100644 modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/utils/useItemDrag.js
error: could not apply bbb6bf37a80b... LPS-109717 Do not deactivate item when dragging from Topper
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
jpince@jpince /media/jpince/l/m (bchan-master) $ git status
On branch bchan-master
You are currently cherry-picking commit bbb6bf37a80b.
  (fix conflicts and run "git cherry-pick --continue")
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

Changes to be committed:

	modified:   modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/utils/useItemDrag.js

Unmerged paths:
  (use "git add <file>..." to mark resolution)

	both modified:   modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/useDragAndDrop.js
```

Can you please try cherry-picking onto BChan's branch and resolving any conflicts there? then resend. Thank you!

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2863. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2864. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
