### PR TITLE
LPS-92968 Use liferay-npm-scripts inside site-admin-web

### PR DESCRIPTION
**Pull request by drewbrokke**

### CODE REVIEW

**Comment by drewbrokke** [comment]
cc @diegonvs

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/p2kmgcl/liferay-portal/pull/315. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
