### PR TITLE
[TS] LPS-104398

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-104398

From @joshuacords:

> Problem: Notifications for Web Content always directed users to the root folder (of the staging site if local staging).
> 
> Solution: Proposed here https://liferay.slack.com/archives/CMFC54M1N/p1573508487009900 have the Notification redirect to the article's direct folder (and to the article's site if staging).
> 
> Most of the complication was in the JournalArticleStagedModelDataHandler where we need to update the notification to contain the proper URLs in the case of having a subscriber on a Live site in Local Staging. There's no Liferay utilities to help us, so it is almost completely manual manipulation. Similarly, in the getFolderURLViewInContext(), manipulating the URL in the case of staging is manual. I kept the liferayPortletResponse as the primary way to generate the URL. It's preferred because that URL will contain the p_p_auth token id which we have no access to without the Response.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @joshuacords @ChrisKian,

Adding the method getFolder URLView Context() to Local ServiceImpl class seems to not to be the correct place, Could you please find a better place to put it? I tend to think we should use an utility class if you want to share the code.

Also, the article.getFolder() can return null or an exception (Home folder is not a real folder), we should check it since we can have a null pointer exception.

cc: @dacousalr

**Pull request closed without merging**
