### PR TITLE
LPS-81931 Also add the related page template entry if it doesn't exist

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@ealonso, unit test failures are present in master too

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/187. [See changes here.](https://github.com/ealonso/liferay-portal/compare/25d2bf8f9b4b~2...25d2bf8f9b4b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
