### PR TITLE
LPS-108342 There aren't any debug traces in JournalArticleIndexer, that makes difficult to diagnose indexation issues during full reindex

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-108342

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84445. [See changes here.](https://github.com/ealonso/liferay-portal/compare/9a9b1d284216~1...9a9b1d284216) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
