### PR TITLE
LPS-78564 Journal analytics gathering

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55989. [See changes here.](https://github.com/ealonso/liferay-portal/compare/f54cf5393f54~4...f54cf5393f54) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55990. [See changes here.](https://github.com/ealonso/liferay-portal/compare/ce5914127dee~5...ce5914127dee) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
