### PR TITLE
LPS-107874 - Update endpoint to accept time range and interval

### PR DESCRIPTION
**Pull request by darquesdev**
@andresfulla @dgarciasarai

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85215. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
