### PR TITLE
LPS-98897 buildLang

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76490. [See changes here.](https://github.com/ealonso/liferay-portal/compare/a3ecbc469b03~2...a3ecbc469b03) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76491. [See changes here.](https://github.com/ealonso/liferay-portal/compare/c311db54c8ae~3...c311db54c8ae) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
