### PR TITLE
Optionally update layoutData on updateFragmentEntryLinkContent

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
:rockte:

**Comment by victorg1991** [comment]
🚀

**Pull request closed without merging**
