### PR TITLE
[TECHNICAL-SUPPORT] LPS-97647

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-97647

/cc @achaparro

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/334. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
