### PR TITLE
LPS-77331 Asset display pages mapping

### PR DESCRIPTION
**Pull request by p2kmgcl**
/cc @jbalsas
/cc @jkappler

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
@p2kmgcl @jkappler rebase errors and sf errors, please resend, 😂 😂 😂

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
