### PR TITLE
LPS-82646 UI broken after saving Web Content with characters outside UTF-8

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
cc:// @sergiogonzalez

**Comment by sergiogonzalez** [comment]
👍

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61027. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
