### PR TITLE
LPS-77686 Create view to configure a content layout (Backend)

### PR DESCRIPTION
**Pull request by jkappler**
@ealonso, backend part of LPS-77686
cc:// @p2kmgcl

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by jkappler** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/55124

**Pull request closed without merging**
