### PR TITLE
LPS-76579 Use optional to get tags to merge since tag could be already renamed

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
@ealonso, sent here: https://github.com/brianchandotcom/liferay-portal/pull/53829

**Pull request closed without merging**
