### PR TITLE
LPS-75887 Use only direct children to get the order

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
cc @p2kmgcl

**Comment by pavel-savinov** [comment]
cc @carloslancha

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/carloslancha/liferay-portal/pull/138. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
