### PR TITLE
LPS-124122 Make staging work with menu display fragment configuration

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/victorg1991/liferay-portal/pull/344. [See changes here.](https://github.com/ealonso/liferay-portal/compare/ee46d3c60ca7~2...ee46d3c60ca7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
