### PR TITLE
LPS-106053 Pass renderRequest

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83083. [See changes here.](https://github.com/ealonso/liferay-portal/compare/30e95cbe3bb6~5...30e95cbe3bb6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83169. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
