### PR TITLE
LPS-72671

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @ealonso,

Attached is an update for http://issues.liferay.com/browse/LPS-72671.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:reopen

**Comment by jonmak08** [comment]
Hey @alee8888,

Do you know why this source formatter is throwing an error?  I tried looking at the issue in the code, but could not find an issue with where it was complaining about.

Thanks!

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49286. [See changes here.](https://github.com/ealonso/liferay-portal/compare/7eb7d18~1...7eb7d18) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
