### PR TITLE
Lps 107002 3

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @katienesterovich

Notes from Katie:
> https://issues.liferay.com/browse/LPS-107002
> 
> The ability to view scheduled web content existed in 6.1.X. In 6.1, `scheduled` Journal Articles had a workflow `status` of 0 (`approved`) and the related Asset Entry had a `visible` status of 1 (true). In 7.3 the workflow status is 7 (`scheduled`) and the asset `visible` column is marked 0 (false). This pull request aims to fix that. 
> 
> - `showScheduled` and `showNonindexable` parameters allow the scheduled entries to be displayed in 'Related Assets' when scheduling an event. 
> 
> - In an article with workflow, when the article is in a pending status, it is not approved nor scheduled. The article is only marked scheduled once it has been approved within the workflow. In other words,`scheduled` status is only assigned to `approved` articles. Therefore, we can say that a `scheduled` article is `approved`- and if an `approved` article is visible, then a `scheduled` article should also be visible. **This change previously caused a test failure** in https://github.com/brianikim/liferay-portal/pull/89, so I modified the test to reflect the changes.
> 
> - When a journal article is created, it is first given a `draft` status (regardless of what the actual status is). It then goes through a default workflow which sets the correct status. However, that does not reflect in the related asset entry. To fix that, I added an `updateAsset` method to the end of `updateStatus`. 
> 
> - Asset publisher will not display `scheduled` web content, since it's not `displayable`. (Displayable implies that the article is approved to be shown to public at current time). However, we want our users to view the scheduled articles from the event scheduler, so I added a check to display the asset if `isVisible()`. From local testing, no scheduled articles display in the regular Asset Publisher, only if a direct link is given (such as one from the event scheduler). 
> 
> I have tested this fix locally and was successful using no workflow and the 1-person approval workflow. I am able to see the scheduled events in the search container when selecting my related assets, I am able to see the selected resources in the event 'View Details', and I am able to view the full asset entry in an asset publisher given a link from the event. 
> 
> NOTE: this fix is specific to Basic Web Content entries and does not address a similar issue with blog entries.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @dacousalr,

Could you please take a look at it?

Regards,
Eudaldo.

**Comment by dacousalr** [comment]
Hi @SamZiemer, @katienesterovich,

With only the first commit this issue would be solved.

The second commit seems to be right but it would be related to a different bug discovered while fixing the current one. In my opinion, this should be analyzed in a different issue.

The rest of the commits are based on the premise that "... we can say that a scheduled article is approved- and if an approved article is visible, then a scheduled article should also be visible".

I am afraid that we cannot say that necessarily. Besides, these changes may have impact on other parts. Could you elaborate a little bit more about which visible effects are thought to be fixed by introducing these commits?

Thanks in advance

**Comment by ealonso** [comment]
@SamZiemer @katienesterovich please see the @dacousalr comment and resend.

Thanks!!

**Comment by katienesterovich** [comment]
Hey @ealonso, 
Thanks for your feedback! 

Here is some clarification for the fixes I proposed: 
- 1920848bce3d9fcdaffda0b78ed0db7b748faf24 allows you to select scheduled assets, you're correct. However, you cannot see the scheduled asset in the Event once you save and view the Event details. Here is a screenshot comparing an event with an active WC and a scheduled WC.
Only parameter fix

- The above issue is then fixed with 2b364b2 and 8640771; Web content created _after_ these commits are applied is visible in the event details. 

- 0a5de38970460940d4683bb7934bab104d932ff1 fixes an issue where clicking scheduled WC in the event would redirect us to an asset publisher displaying an error (see below). That's because scheduled WC is not `displayable` in asset publisher. 0a5de38970460940d4683bb7934bab104d932ff1 fixes that by checking if an asset is visible.

image

From manual testing I didn't notice any regressions. But I agree, this is a significant change that has the potential to affect other cases. 

Please let me know how you would like to proceed, I'm happy to make modifications and/or split the commits into separate tickets. 

Thanks! :)

**Comment by dacousalr** [comment]
Thanks for your clarifications, @katienesterovich,

> ...However, you cannot see the scheduled asset in the Event once you save and view the Event details. Here is a screenshot comparing an event with an active WC and a scheduled WC.

I would prefer to change the condition in https://github.com/liferay/liferay-portal/blob/318f05cfba3e5cf9ef72763de5f1af2e00fc7ff3/modules/apps/asset/asset-taglib/src/main/java/com/liferay/asset/taglib/servlet/taglib/AssetLinksTag.java#L214 to check if `!assetEntry.isVisible() && assetRenderer.getStatus() != WorkflowConstants.STATUS_SCHEDULED` 

> 0a5de38 fixes an issue where clicking scheduled WC in the event would redirect us to an asset publisher displaying an error (see below). That's because scheduled WC is not displayable in asset publisher. 0a5de38 fixes that by checking if an asset is visible.

For this case, I would suggest that the link is not shown if it is not displayable.

What do you think about these two points, @ealonso?

**Comment by katienesterovich** [comment]
Thanks again for your feedback @dacousalr! I meant to tag you in my previous comment but tagged Eudaldo instead, my apologies. 

Once we hear back from @ealonso I can make the suggested adjustments. 
Thanks!

**Comment by jkappler** [comment]
Just started reviewing :)

**Pull request closed without merging**
