### PR TITLE
LPS-115454 Don't rely on name attribute, and create unique ID's for the inputs prefixing them with randomNamespace generated by refererPortletName. Since some inputs are in a loop, we also add at the end the value. Apply to other inputs outside of the loop as well

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/842. [See changes here.](https://github.com/ealonso/liferay-portal/compare/9b1c3af2f102~2...9b1c3af2f102) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
