### PR TITLE
Lps 138156 add templates to mapping fields

### PR DESCRIPTION
**Pull request by lfbesada**

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1297401_73

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/5655. [See changes here.](https://github.com/ealonso/liferay-portal/compare/3cc8d31c7fec~12...3cc8d31c7fec) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/5667. [See changes here.](https://github.com/ealonso/liferay-portal/compare/66b5566ceff2~13...66b5566ceff2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/5668. [See changes here.](https://github.com/ealonso/liferay-portal/compare/b2aef7199471~12...b2aef7199471) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
