### PR TITLE
Lps 111915

### PR DESCRIPTION
**Pull request by SamZiemer**
[LPS-111915](https://issues.liferay.com/browse/LPS-111915)

**Observed Error**: Users are unable to preview the display page template of a web content before the web content is published.

**Root Cause**: To preview the draft web content, the portal fetched the latest _Approved_ version of the article; however, newly created drafts don't have an _Approved_ version yet.

**Solution:** 
Currently, the article to be viewed is fetched by its `groupId` and `articleId` and has a filter of `WorkflowConstants.STATUS_APPROVED` later applied to the query, seen in 
https://github.com/liferay/liferay-portal/blob/7e7782a8cfb106ddfb68231dc8f217633b4a8110/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/internal/util/JournalContentImpl.java#L347-L348
The solution bypasses that method and calls `getDisplay()` directly, eliminating the need for the _Approved_ version of the article to be retrieved and allowing the user to view the _Draft_ article.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:stable

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
@SamZiemer @amandaaakwok Could you please take a look at my comment [here](https://issues.liferay.com/browse/LPS-111915?focusedCommentId=2134053&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2134053)?
Thanks!

**Comment by pavel-savinov** [comment]
ci:close

**Pull request closed without merging**
