### PR TITLE
LPS-116030 Don't create default vocabulary when users doesn't specify it explicitly

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
