### PR TITLE
[TECHNICAL-SUPPORT] LPS-83081

### PR DESCRIPTION
**Pull request by pedroqueiroz**
Hi @ealonso. @JosemariaMunoz sent me this PR related to DDMStructure. 

It looks good to me, but since it is changing the Asset Publisher code, I'm forwarding this to you.

Let me know if you need anything from our side.

Thanks!

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/pedroqueiroz/liferay-portal/pull/165. [See changes here.](https://github.com/ealonso/liferay-portal/compare/93d626e50c5c~3...93d626e50c5c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
