### PR TITLE
LPS-92042

### PR DESCRIPTION
**Pull request by giros**
https://issues.liferay.com/browse/LPS-92042

### CODE REVIEW

**Comment by giros** [comment]
ci:test:sf

**Comment by giros** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
hi @giros, @ealonso is ooo, so I was reviewing the PR. Just one question. We also use the scope group in other places like membership requests. Should we also change it in those cases to use live group id?

Thanks!

**Comment by giros** [comment]
hi @jkappler, I believe that we should change them as well, so probably I just missed them. I'll extend my fix and resend. Shall I sen it to you directly then?

**Comment by jkappler** [comment]
hi @giros, will be ooo until the 28th. You can send it to @ealonso or @pavel-savinov who will be at the office at the end of the week

**Pull request closed without merging**
