### PR TITLE
LPS-112114 Publish schema version as OSGI property for JournalPortlet…

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @brianikim

Notes from Brian:
> Solution for this particular case is to publish schema version as an OSGI property for JournalPortletDataHandler so that the JournalPortletDataHandler is loaded with the correct schema. The ticket itself was created in that particular style as recommended by MCD so that other cases can be fixed through it.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:stable

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
