### PR TITLE
LPS-88611 Show portlet name since there can be different usages on the same page

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66299. [See changes here.](https://github.com/ealonso/liferay-portal/compare/20e9cf1c8c19~8...20e9cf1c8c19) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66300. [See changes here.](https://github.com/ealonso/liferay-portal/compare/2a5d32c4f478~8...2a5d32c4f478) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
