### PR TITLE
LPS-105628 Use constant

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
918ff45, 74f9768, 3b6cd14, 74099bf, 85a7fc5 have java

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
rebased with master and fixed rebased error

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/sandrodw3/liferay-portal/pull/171. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
