### PR TITLE
[TS] LPS-111194

### PR DESCRIPTION
**Pull request by ChrisKian**
From @kevhlee:

> <https://issues.liferay.com/browse/LPS-111194>
> 
> The issue was that a notification email to review the latest version of a journal article would be sent for each version. For example, if a previous version had a review date of 03/20/20 and the latest version had a review date of 03/22/20, the portal would send review notification emails for both dates. A review notification email should only be sent for the latest version of a journal article. To fix this issue, I modified and corrected `checkArticlesByReviewDate()` to only check and email the latest versions of journal articles. My solution makes the assumption that each journal article can only have one latest version.
> 
> With regards,
> Kevin

CC @wanderlast

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/51. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
