### PR TITLE
[TECHNICAL-SUPPORT] LPS-70514

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @mbowerman

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@ealonso This solution seems like what you wanted on https://github.com/sergiogonzalez/liferay-portal/pull/3796 however with this fix in place, the vocabulary is rendered useless until the user goes in an manually changes the associated asset types. Not sure if that's what you were looking for.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/47045. [See changes here.](https://github.com/ealonso/liferay-portal/compare/5033f49~4...5033f49) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/47047. [See changes here.](https://github.com/ealonso/liferay-portal/compare/c4878e8~4...c4878e8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
