### PR TITLE
LPS-84801

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/preston-crary/liferay-portal/pull/583. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
