### PR TITLE
LPS-78872 Make fragment display portlet non-ajaxable to avoid AlloyEditor resources problems

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
@p2kmgcl Could you please take a look at fc728ba? Thanks!

**Comment by pavel-savinov** [comment]
ci:test

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57035. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
