### PR TITLE
LPS-107552 Add the logic in a missing place

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84366. [See changes here.](https://github.com/ealonso/liferay-portal/compare/5910769be78d~1...5910769be78d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
