### PR TITLE
[Technical Support] LPS-56711 Move the query logic from view_dynamic_list.jspf to public API

### PR DESCRIPTION
**Pull request by zsigmondrab**
Hi Eudaldo (sorry about mixing your names),

we have created a solution for moving the asset entry listing logic to a common place which we discussed about with Julio here: https://github.com/juliocamarero/liferay-portal/pull/3338

Could you please take a look at and share your opinion to us?

Thank you in advance,
Zsigmond

### CODE REVIEW

**Comment by zsigmondrab** [comment]
ci:retest

**Comment by zsigmondrab** [comment]
ci:retest

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/juliocamarero/liferay-portal/pull/3541. [See changes here.](https://github.com/ealonso/liferay-portal/compare/bc67c48~2...bc67c48) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
