### PR TITLE
LPS-39511 User is unable to access Web Content permissions although they are defined in regular role.

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @pei-jung,

After reviewing your changes, I've seen it's cause a regression bug, now we have the permission action in some portlets of control panel (tags, recycle bin, sites, site templates, page template, system settings, ...)

You can see how it looks like in master:

tags_-_liferay

and how it looks like with your changes:

tags_-_liferay

Could you take a look at it? Let me know if I can help you with anything else.

Thanks.

**Comment by pei-jung** [comment]
Hey @ealonso,

I added a new boolean in `PortletDisplay` so that we don't have to depend on `portletDisplay.isShowConfigurationIcon()` to filter the permissions icon.

However, I noticed that the permissions configuration in the admin portlet doesn't do anything. Any permissions defined in there don't take effect in the app nor the admin portlet. The steps I took to test this is:

- Create user testUser
- Create role testRole
- Define `Access in Site Administration` permission to testRole
- Assign testUser to testRole
- Go to Web Content > Permissions on the top right corner
- Check `view`, `configuration`, `permissions` for testRole
- Add Web Content Display to the page
- Sign in as testUser 

Result: testUser cannot access Web Content in Site Admin and cannot see the configuraiton/permissions configurations in Web Content Display's options menu.

And looking at 6.2, there's no permissions configuration for portlets in the control panel (see https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/portal/render_portlet.jsp#L793-L802). I think we're not supposed to show permissions configuration in admin portlets, so I have done that with my fix. Let me know if I'm wrong.

One more issue I noticed is that the Web Content Display portlet doesn't show up when there's no content. It shows if the permission for configuration is defined but not for permissions. So make sure there's content in the WCD portlet when testing.

Thanks!

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/42754. [See changes here.](https://github.com/ealonso/liferay-portal/compare/e2fe724~1...e2fe724) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @pei-jung,

I think your fix is the correct one, we shouldn't allow users to configure permissions on control panel porltets.

When you are adding permission to Web Content those affects only to Web Content portlet, for Web Content Display you should go to **Site Administration > Applications > Web Content Display**

Regards,
Eudaldo.

**Pull request closed without merging**
