### PR TITLE
LPS-103454 Simplify

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82429. [See changes here.](https://github.com/ealonso/liferay-portal/compare/ff8c84f8df45~1...ff8c84f8df45) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82461. [See changes here.](https://github.com/ealonso/liferay-portal/compare/5969187e9e44~2...5969187e9e44) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82467. [See changes here.](https://github.com/ealonso/liferay-portal/compare/ec38c77e7974~3...ec38c77e7974) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
