### PR TITLE
[TS]LPS-95581  Poor performance of site load with many users

### PR DESCRIPTION
**Pull request by drewbrokke**
https://issues.liferay.com/browse/LPS-95581

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73853. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
