### PR TITLE
LPS-75578 Regenerate service code

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53623. [See changes here.](https://github.com/ealonso/liferay-portal/compare/fc7c58e~3...fc7c58e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
