### PR TITLE
LPS-101134 Integration test to verify isConvertible returns false for customizable Widget Page

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
ci:test:relevant <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78117. [See changes here.](https://github.com/ealonso/liferay-portal/compare/be72b33c9adb~1...be72b33c9adb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
