### PR TITLE
LPS-95634

### PR DESCRIPTION
**Pull request by samuelkong**

### CODE REVIEW

**Comment by samuelkong** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by samuelkong** [comment]
@ealonso 
I added some additional commits to this pull request.

- Applied the same fix to Templates
- Applied a similar fix to Structure (it's a little different because structure doesn't use `xxxDisplayContext.getRedirect`)
- @sunnygao also noticed a XSS issue with the cancel button so she fixed this also, LPS-95782

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73351. [See changes here.](https://github.com/ealonso/liferay-portal/compare/9c28a0bff309~1...9c28a0bff309) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by samuelkong** [comment]
@ealonso 
Since you switched to `aui:button`, you also don't need to include `HtmlUtil.escapeAttribute()` in the JSP because `aui:button` will call `escapeAttribute()` automatically for you.

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73357. [See changes here.](https://github.com/ealonso/liferay-portal/compare/96b90b84bdea~2...96b90b84bdea) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
@samuelkong thanks!! I've updated the pull, see https://github.com/brianchandotcom/liferay-portal/pull/73357

**Pull request closed without merging**
