### PR TITLE
LPS-76010

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-76010

About https://github.com/ealonso/liferay-portal/pull/1249/commits/5935ee93aa2a281c9f7790939e9497055b611d0c commit, I am changing the taglib because my changes are only applied to liferay-asset and liferay-ui seems to be some kind of compatibility taglib that uses a old version of modules.
If I am missing something about that, please let me know

After my changes, in **resources/asset_links/page.jsp** the code that generates the URLs, is almost identical to a fragment of **AssetPublisherHelperImpl.getAssetViewURL**:
  - https://github.com/jorgediaz-lr/liferay-portal/blob/0535d618cbbbbdbf070092d64756219679afb832/modules/apps/web-experience/asset/asset-taglib/src/main/resources/META-INF/resources/asset_links/page.jsp#L87-L115
  - https://github.com/jorgediaz-lr/liferay-portal/blob/0535d618cbbbbdbf070092d64756219679afb832/modules/apps/web-experience/asset/asset-publisher-impl/src/main/java/com/liferay/asset/publisher/internal/util/AssetPublisherHelperImpl.java#L529-L574

Perhaps we should move it to a common place, but they belong to different modules. 
What do you think?

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53271. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jorgediaz-lr** [comment]
Thank you, @ealonso

**Pull request closed without merging**
