### PR TITLE
LPS-108921 Keep old single selection around for backwards compatibility

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
> Hey @ambrinchaudhary 
> 
> I've add support for callers to select single/multiple selection via the portlet URL, and restored the old code for backwards compatibility (right now it is a bit risky to remove all references).
> 
> If you're ok with these changes, please forward the pull request to @ealonso.
> 
> Thanks!

### CODE REVIEW

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Sent here: https://github.com/brianchandotcom/liferay-portal/pull/86607

**Comment by ealonso** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/86607

**Pull request closed without merging**
