### PR TITLE
LPS-121693 Display View Usages action only if feature flag is enabled

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/ruben-pulido/liferay-portal/pull/369. [See changes here.](https://github.com/ealonso/liferay-portal/compare/f482b5a87121~15...f482b5a87121) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
