### PR TITLE
LPS-44217 semver

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
This PR is meant as a seed for resolving LPS-44217.
The backend implementation is pretty complete, but the user interface still needs a real solution. I simply used an encoding on the existing input field which is compatible with the previous, existing usages:

`<hostname>[;<languageId>][,<hostname>[;<languageId>]]*`

e.g. `english.ca;en_US,francais.ca;fr_FR`

/cc @JorgeFerrer @AngeloYoun @igorarouca

**Comment by rotty3000** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2498. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
