### PR TITLE
[TECHNICAL-SUPPORT] LPS-76334

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by ealonso** [comment]
Hey @jonathanmccann,

This code is part of collaboration team, Could you please send this one to @sergiogonzalez?

Thanks!!
Eudaldo.

**Comment by sergiogonzalez** [comment]
I just sent it to Brian https://github.com/brianchandotcom/liferay-portal/pull/53613

**Comment by jonathanmccann** [comment]
Thanks for forwarding this @sergiogonzalez

**Pull request closed without merging**
