### PR TITLE
LPS-100945 Add link to default fragments

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78127. [See changes here.](https://github.com/ealonso/liferay-portal/compare/9aadff4fa686~1...9aadff4fa686) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
