### PR TITLE
LPS-91519 Removing code duplication

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69287. [See changes here.](https://github.com/ealonso/liferay-portal/compare/cd2be2470eec~11...cd2be2470eec) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69302. [See changes here.](https://github.com/ealonso/liferay-portal/compare/d0d217cc5ba3~11...d0d217cc5ba3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
