### PR TITLE
LPS-96564

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Sent here: https://github.com/brianchandotcom/liferay-portal/pull/74632

**Comment by jkappler** [comment]
ci:close

**Comment by IstvanD** [comment]
Thank you @adolfopa for the additional modifications.
I would like to ask one more question about the overall solution:
as I see, the non-admin user cannot select the Global site now, while before the fix, they could.
Is this intended behavior or something that should be addressed?

Thank you and best regards,
István

**Comment by adolfopa** [comment]
Hey @IstvanD,

The intended behaviour is that the Item Selector should only list those groups for which the user has VIEW permission.  Whether regular users should see the Global scope or not is a question @ealonso  may be able to answer.

If it should be visible, then we should fix GroupPermission to make it visible (or find an alternative if that cannot be implemented for whatever reason).

Thanks!

**Pull request closed without merging**
