### PR TITLE
LPS-55583

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-55583](https://issues.liferay.com/browse/LPS-55583).<br><br>Hey @ealonso, all of my local tests passed, but we'll see if this passes on github

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:retest

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28189. [See changes here.](https://github.com/ealonso/liferay-portal/compare/13ece56~1...13ece56) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/evannagayama/liferay-portal/pull/449. [See changes here.](https://github.com/ealonso/liferay-portal/compare/006fc71~1...006fc71) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/35045. [See changes here.](https://github.com/ealonso/liferay-portal/compare/349c1fd~3...349c1fd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/evannagayama/liferay-portal/pull/450. [See changes here.](https://github.com/ealonso/liferay-portal/compare/349c1fd~3...349c1fd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/35107. [See changes here.](https://github.com/ealonso/liferay-portal/compare/4ca716a~5...4ca716a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/35108. [See changes here.](https://github.com/ealonso/liferay-portal/compare/b9f8a08~5...b9f8a08) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
