### PR TITLE
J cords lps 99857 2

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-99857

Hello @ealonso,

Because the older change in https://github.com/ealonso/liferay-portal/pull/2525 was still running into test failures where it was hard to tell if the test was at fault or not. And because allowing the portletRequestModel to be null is only applicable while staging. I've changed the approach just to check is an Import is in process. 
The previous failing tests are all passing on my machine and this resolves the issue.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77979. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
