### PR TITLE
LPS-55583

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-55583](https://issues.liferay.com/browse/LPS-55583).<br><br>

### CODE REVIEW

**Comment by ealonso** [comment]
Hi @drewbrokke,

Your pull break some test, Could you please fix it and resend?

I think the solution could be the same that I implemented on 1ce8643

Regards,
Eudaldo.

**Comment by drewbrokke** [comment]
Hey @ealonso, the errors are coming from the UserGroupStagedModelDataHandlerTest, which is the class I ended up leaving in core.  Any ideas about a way to address that one?  I'm still trying to figure it out...

**Comment by ealonso** [comment]
Hey @drewbrokke, we forget to register the UserGroupStagedModelDataHandlerTest.

I've added the code necessary for it and I've sent a pull to Brian, please see my last commit on https://github.com/brianchandotcom/liferay-portal/pull/28319

Regards,
Eudaldo.

**Comment by drewbrokke** [comment]
Thanks @ealonso!

**Pull request closed without merging**
