### PR TITLE
LPS-91210 Update entity models

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68664. [See changes here.](https://github.com/ealonso/liferay-portal/compare/3303d6619a50~1...3303d6619a50) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
