### PR TITLE
LPS-78032 Delete removed layout from default site navigation menu to aboid broken menu links

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
We agreed with @JorgeFerrer and Bea that for now we just delete Layout item from the default menu to maintain it's consistency. For one of the upcoming sprints we'll create a new Story to inform the administrator that the Layout is in use in the navigation menu.

**Comment by pavel-savinov** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55455. [See changes here.](https://github.com/ealonso/liferay-portal/compare/6b90405597cd~1...6b90405597cd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
