### PR TITLE
[TS] LPS-92252

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-92252

From @jrao:

> Make portletRequestModelFactory available to template context

Let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/7492. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
