### PR TITLE
LPS-79498 checking role for all groups when groupid is zero

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by ealonso** [comment]
@dacousalr @linolaoj 

Could be possible to add some test? This is a really risky change and I would like to have some test that ensure everything is working fine.

Regards,
Eudaldo

**Comment by linolaoj** [comment]
Hi @ealonso, I'll add some test and resend.
Thanks!

**Comment by ealonso** [comment]
Thanks!!

**Pull request closed without merging**
