### PR TITLE
LPS-174322 Remove nonexistent Class/package

### PR DESCRIPTION
**Pull request by ling-alan-huang**
https://github.com/liferay/liferay-portal/commit/150c429ede387a597e34170e0d11881f49528a47#diff-3dc9767c1fe2d561f37033c24c67cefe84e9720d0e505228b79da0c5404f05ca

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
@ealonso SF complains this issue.

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Thanks @ling-alan-huang, I just sending a revert for it, because it is causing a blocker, so it should not be necessary at this moment. But, I'm going to need it when I fix the problem and send again the pr.

**Pull request closed without merging**
