### PR TITLE
LPS-107685 If backgroundImage is not set don't create FragmentImage

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/ruben-pulido/liferay-portal/pull/166. [See changes here.](https://github.com/ealonso/liferay-portal/compare/cf23b930e1a2~1...cf23b930e1a2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
