### PR TITLE
LPS-74647 Large images display outside RSS portlet border

### PR DESCRIPTION
**Pull request by dustinryerson**
Hi @ealonso,

This is an update for https://issues.liferay.com/browse/LPS-74647.

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:retest

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Sent to @brianchandotcom here: https://github.com/brianchandotcom/liferay-portal/pull/51534

**Comment by dustinryerson** [comment]
Thank you, @jkappler!

**Pull request closed without merging**
