### PR TITLE
LPS-103818 Use item selector in configuration view

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @ealonso 
This replaces the asset browser in Journal by an Item Selector (I still need to change things so that both Draft and approved elements show up; I wanted to do that in a different ticket to discuss this with you first.)
Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
