### PR TITLE
LPS-64005 use article group id when fetching ddm structure and template by key

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by achaparro** [comment]
Hey @pavel-savinov,

I think that the tests are failing properly because there is a null pointer exception creating a new journal article since article is null here:
m/pavel-savinov/liferay-portal/blob/LPS-64005/modules/apps/web-experience/journal/journal-web/src/main/resources/META-INF/resources/edit_article.jsp#L56

**Comment by ealonso** [comment]
Hey @pavel-savinov,

Could you fix de NPE and resend?

Thanks!!!

**Pull request closed without merging**
