### PR TITLE
LPS-78013 Adding Portlet Permission Check

### PR DESCRIPTION
**Pull request by balazssk**
Hi Eudaldo,

Hope the subrepo changes were made so I'm submitting this PR to liferay-portal.
https://issues.liferay.com/browse/LPS-78013

Can you please have a look at this?

Thanks,
Balazs

### CODE REVIEW

**Comment by balazssk** [comment]
Hi @ealonso ,
Have you had a chance to look this through?

Thanks

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/145. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by balazssk** [comment]
Thanks @ealonso !

**Pull request closed without merging**
