### PR TITLE
LPS-77375 Remove unused css

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55198. [See changes here.](https://github.com/ealonso/liferay-portal/compare/ee50058~2...ee50058) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
