### PR TITLE
LPS-71243 build.gradle

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
Hey @shuyangzhou,

I'm trying to extract Trash Service to OSGI modules.

I've created 6227758, the modular wrappers to wrap the calls for old services, right now, it is working fine for test in modules (integration and poshi), but I'm getting this error for test in portal-impl:

```
Error message

This class is deprecate and replaced by com.liferay.trash.service.impl.TrashEntryLocalServiceImpl
Traza

java.lang.UnsupportedOperationException: This class is deprecate and replaced by com.liferay.trash.service.impl.TrashEntryLocalServiceImpl
	at com.liferay.portlet.trash.service.impl.TrashEntryLocalServiceImpl.getEntries(TrashEntryLocalServiceImpl.java:203)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:163)
	at com.liferay.portal.spring.transaction.DefaultTransactionExecutor.execute(DefaultTransactionExecutor.java:54)
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:58)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
	at com.liferay.portal.spring.aop.RetryAdvice.invoke(RetryAdvice.java:46)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
	at com.liferay.portal.service.ServiceContextAdvice.invoke(ServiceContextAdvice.java:39)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)

```

Do you know if I need to add something else to make tests work? or Do I need to extract all those test to their respective module?

Regards,
Eudaldo.

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
ci:retest

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/973. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
