### PR TITLE
LPS-107685 Set definition in PageElements of type Column

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84104. [See changes here.](https://github.com/ealonso/liferay-portal/compare/8f3f4d2c9250~14...8f3f4d2c9250) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
