### PR TITLE
LPS-100248

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-100248

Hello Eudaldo,

Please let me know if this should go to someone else.

Users that belong to a site can bypass Control Panel permissions by using URL http://localhost:8080/group/control_panel/manage/-/sites to access the Control Panel Sites. The portal property `sites.control.panel.members.visible` has the default value set to true and allows this behavior to occur. By using the URL, the user can view Membership Type, Active status, and private sites which can be argued should not be viewed unless given proper permissions.

The default value should be changed to false to prevent this behavior to occur.

Let me know if there are any questions or comments about this.
Thank you.

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77386. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
