### PR TITLE
[TS] LPS-111067, LPS-112103

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-111067
https://issues.liferay.com/browse/LPS-112103

Although this issue touches many different portlets, they all have the same theme of correcting the displayStyle.  This seems mostly WEM related, but if you disagree, I can forward it elsewhere.

From @wanderlast 

> This issue is a fix for an issue that covers a broad range of portlets, so this may need to be looked at by multiple teams. I've purposely kept the different portlets in separate commits so that we can hopefully easily remove them from the pull if the teams decide they want the current behavior to persist. I've tried to sync the behavior with 7.1.x (where the fix that caused this issue does not exist), but many features/portlets exist in Master that do not exist in 7.1 so many of these are merely just a best guess that the team would prefer the display style to not reset. Specifically, the issue is that display styles are not actually passed by parameter when navigating between admin portlets (e.g. going from Web Content to Blogs and then back). Therefore the display style will always reset to whatever the default value is given when retrieving the parameter. It was caused by LPS-90549 which changed the method of retrieving display styles for a seemingly unrelated bugfix. It appears we've followed that design pattern afterwards which would explain the large number of instances of this issue. I've verified that my changes do not appear to make the bug reoccur.
> 
> One notable decision that was made was that in, certain portlets, there are multiple display contexts (e.g. should the user menu and organizations menu always show the same display style?). It's fairly unclear whether these different menus should share the same display style or not among each other and there are multiple portlets where this occurs. Why this is an issue is that the display style is typically saved in PortalProperties using a combination of the portlet as the namespace and "display-style" as the key. However, if multiple display contexts share the same portlet and therefore the same namespace, than the key must also be distinct for them to remain separate entities. For most areas, I've erred on the side of caution and created separate keys for these redundant entries, using the naming scheme "display-style" for any base contexts that might exist for the portlet (e.g. SiteMembershipsDisplayContext), while following the naming scheme of "display-style-class-name" for other keys (e.g. "display-style-select-organizations" in SelectOrganizationsDisplayContext). The most notable exception is that, due to a specific ticket, Organizations between the site membership portlet and the users admin portlet are kept the same since that ticket outlined it as intentional.
> 
> I specifically did not "fix" this behavior in item selectors since it doesn't strike me as expected behavior, but I am more than happy to make the changes if you feel that it would be better that way.
> 
> LPS-112103 is a related issue fix where the toolbar in Journal also did not properly retrieve the changed display upon navigation, showing a separate default value. I didn't notice this behavior in other places while testing, but it's possible I may have missed an instance.
> 
> Since this is a fairly large fix, please let me know if I can clarify anything or look into anything further for you. Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @wanderlast,

First of all, sorry for the delay.

I have one question about your changes, What happen with the management toolbar? Looking at the code it seems to be we are using the default value instead of the preferences value.

see BaseManagementToolbarDisplayContext#getDisplayStyle():
```
protected String getDisplayStyle() {
	return ParamUtil.getString(
		request, "displayStyle", getDefaultDisplayStyle());
}
```

In journal we are overwriting this method, but in the other cases we are not doing that.

Regards,
Eudaldo.

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/440. [See changes here.](https://github.com/ealonso/liferay-portal/compare/31289a918a2f~2...31289a918a2f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
I'm sending only https://issues.liferay.com/browse/LPS-112103

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by wanderlast** [comment]
Hi @ealonso,
I'm sorry for the delayed reply. I didn't see this until you mentioned it on the last PR. When it comes to the specific instance you mentioned BaseManagementToolbarDisplayContext#getDisplayStyle(), I don't believe (or at least do not know of) a good way to handle the ambiguity of the namespace parameter for the base context. Do you have a suggestion on how it could be handled?

**Comment by ealonso** [comment]
Hey @wanderlast,

Related with your pull it is better is you send the code to each team, since you are making changes in a lot of modules.

Could you please send the related changes to Echo Team to liferay-echo github user?, you should send the other ones to the teams in charge of this modules.

Regards,
Eudaldo.

**Pull request closed without merging**
