### PR TITLE
LPS-92042 Let Site Memberships portlet use the live group id for all …

### PR DESCRIPTION
**Pull request by giros**
…it's display logic, just like it already does in it's display contexts

https://issues.liferay.com/browse/LPS-92042

### CODE REVIEW

**Comment by giros** [comment]
ci:test:sf

**Comment by giros** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73744. [See changes here.](https://github.com/ealonso/liferay-portal/compare/e994c484da67~1...e994c484da67) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
