### PR TITLE
LPS-109123 Define the structure layout as the default one by setting its classNameId and structureLayoutKey equals to structure's attributes

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:test:sf

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @leoadb, we have some tests failures, Could you please take a look at it?

**Comment by leoadb** [comment]
@ealonso sure!

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/561. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
