### PR TITLE
LPS-82444 We need to update the display page associated, mostly for listening for changes for staging

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @brianchiu

**Comment by jkappler** [comment]
c:test:relevant

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
Trying it again. The display pages failure was a flaky failure that was solved here:
https://github.com/brianchiu/liferay-portal/pull/1645

The portal smoke failure will still be around though.

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
@jkappler Yup, no unique test failures.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/195. [See changes here.](https://github.com/ealonso/liferay-portal/compare/81da079ba357~1...81da079ba357) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
