### PR TITLE
[TECHNICAL-SUPPORT] LPS-89503

### PR DESCRIPTION
**Pull request by adolfopa**
/cc @brianikim 

Notes from Brian:

> https://issues.liferay.com/browse/LPS-89503
> 
> The issue here is that the returned results in the web content menu pop-up frame that appears when you click to view more menu items is not respecting the pagination.
> 
> The reason for this issue is that the implementation that properly handles pagination results was not implemented for [view_more_menu_items.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/view_more_menu_items.jsp). The fix is to implement the requirement.
> 
> See attached video in the ticket for a more visual description of the behavior.
> 
> Please let me know if you have any questions. Thanks.
> 
> Sincerely,
> Brian Kim

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67357. [See changes here.](https://github.com/ealonso/liferay-portal/compare/3005c7ceb502~1...3005c7ceb502) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
