### PR TITLE
LPS-76165 Image HTML preview processor implementation

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53490. [See changes here.](https://github.com/ealonso/liferay-portal/compare/74b785a~14...74b785a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
