### PR TITLE
[TECHNICAL-SUPPORT] LPS-99992

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @achaparro

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/346. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
