### PR TITLE
LPS-106990 Set layoutTemplateId in TypeSettings when creating widget pages for tests to prevent NPE

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Hi @mwilliams2014
Can you take a look at the warning messages in https://github.com/ealonso/liferay-portal/pull/2686/commits/7a0d51cb379c03ec2c268c746fda7bfb179ed0ce

Maybe the wording can be improved.
Thanks!!

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mwilliams2014** [comment]
@ruben-pulido LGTM!

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/ruben-pulido/liferay-portal/pull/155. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
