### PR TITLE
LPS-79275 Fragment preview frame

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57017. [See changes here.](https://github.com/ealonso/liferay-portal/compare/f98486a7b717~10...f98486a7b717) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57026. [See changes here.](https://github.com/ealonso/liferay-portal/compare/1105c7ba1763~11...1105c7ba1763) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
