### PR TITLE
[TECHNICAL-SUPPORT] LPS-96209

### PR DESCRIPTION
**Pull request by jonathanmccann**
@ealonso,

[This logic](https://github.com/ealonso/liferay-portal/pull/2411/commits/1faeb6cd8a08dee6f0f6a40f32257895532e6311) is the same used in [BlogsEntryLocalServiceImpl](https://github.com/liferay/liferay-portal/blob/master/modules/apps/blogs/blogs-service/src/main/java/com/liferay/blogs/service/impl/BlogsEntryLocalServiceImpl.java#L2440-L2444) and was confirmed to be the correct behavior on PTR-924.

The upgrade process was added as 1.1.7 so that it can be backported to 7.1.x.

Please let me know if you have any questions or concerns.

/cc @dacousalr

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74114. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
