### PR TITLE
LPS-91996 Regen

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/epgarcia/liferay-portal/pull/718. [See changes here.](https://github.com/ealonso/liferay-portal/compare/2ac651ed9e0c~1...2ac651ed9e0c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
