### PR TITLE
[TECHNICAL-SUPPORT] LPS-85863

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Explanation of changes and test results - https://github.com/gregory-bretall/liferay-portal/pull/101

/cc @frankfu926

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
@jonathanmccann @frankfu926
There is no need to check VIEW_CONTROL_PANEL permission for the Control Menu/Product Menu because the Control Panel it is only one section of the Product Menu and we check this permission in the Product Menu logic.
Furthermore, by checking this permission we prevent Contributor from adding CSS class we need and this ends up like this(hiding search bar, logo, etc.):
screen shot 2018-10-01 at 17 54 24

When user has VIEW_CONTROL_PANEL permission, it looks like this:
screen shot 2018-10-01 at 17 55 02

**Pull request closed without merging**
