### PR TITLE
[TECHNICAL-SUPPORT] LPS-78936

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @jonathanmccann,

I'm not completely sure about this fix, Could you please talk with @shuyangzhou or @Preston-Crary about it?

Thanks!!
Eudaldo.

**Comment by ealonso** [comment]
ci:test

**Comment by Preston-Crary** [comment]
@jonathanmccann please resend with a test so we can be sure it works on all our supported DBs, thanks!

**Pull request closed without merging**
