### PR TITLE
LPS-80503 Semantic versioning

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
cc @p2kmgcl

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/254. [See changes here.](https://github.com/ealonso/liferay-portal/compare/8be61f7d1232~4...8be61f7d1232) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
