### PR TITLE
LPS-77596

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/3213 for more information

**Comment by yuhai** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56418. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
