### PR TITLE
LPS-75259 Added check not to export portlet data when propagating changes from site template

### PR DESCRIPTION
**Pull request by JavierMoral**

### CODE REVIEW

**Comment by JavierMoral** [comment]
ci:retest

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
@ealonso, sent to Brian here: https://github.com/brianchandotcom/liferay-portal/pull/52297

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
