### PR TITLE
[TECHNICAL-SUPPORT] LPS-72194

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/migue/liferay-portal/pull/979. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @jonathanmccann,

The VirtualHostFilter is part of the core infrastructure Team, I'm going to forward it to someone in that team.

Regards,
Eudaldo.

**Comment by jonathanmccann** [comment]
Sorry about that! I saw the WCM component on the LPS and went with that. I'll keep that in mind for the future, thanks.

**Comment by ealonso** [comment]
Don't worry about that.

**Pull request closed without merging**
