### PR TITLE
[TECHNICAL-SUPPORT] LPS-106781

### PR DESCRIPTION
**Pull request by jonathanmccann**
I wasn't sure if the template in the test directory needed to be changed or not. If it doesn't need to be modified feel free to toss out that change.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82997. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
