### PR TITLE
[TECHNICAL-SUPPORT] LPS-101182

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78097. [See changes here.](https://github.com/ealonso/liferay-portal/compare/a42a503105f1~2...a42a503105f1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78163. [See changes here.](https://github.com/ealonso/liferay-portal/compare/bb5ec515ad3d~1...bb5ec515ad3d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
