### PR TITLE
LPS-108815 DON'T COMMIT Get and show item children when drag & hover

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
cc @wincent this is for you to review just the last LPS-109145 commit.

@ealonso this is for you to review just the two first LPS-109145 commits (java related). Please do not send it to Brian, just send it back to me if you have any changes to do or let me know if LGTY.

Thanks!

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by wincent** [comment]
> cc @wincent this is for you to review just the last LPS-109145 commit.

If you are referring to https://github.com/ealonso/liferay-portal/pull/2794/commits/2ded2e24dd7ddbac387c9764d4731a0c5c65ba84, looks fine to me.

**Comment by carloslancha** [comment]
> > cc @wincent this is for you to review just the last LPS-109145 commit.
> 
> If you are referring to [2ded2e2](https://github.com/ealonso/liferay-portal/commit/2ded2e24dd7ddbac387c9764d4731a0c5c65ba84), looks fine to me.

nope, this one https://github.com/ealonso/liferay-portal/pull/2794/commits/b04463ff571ac6eddc33b53fef54a0012ac68fb8

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
