### PR TITLE
LPS-90486 Ignore error in case we are not in portlet export/import

### PR DESCRIPTION
**Pull request by jorgediaz-lr**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68091. [See changes here.](https://github.com/ealonso/liferay-portal/compare/5494c3d1b8fb~1...5494c3d1b8fb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
