### PR TITLE
LPS-88424 Make interval a constant

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:test

**Comment by ealonso** [comment]
Hey @brianchiu @kyle-miho,

Do you know if the failing tests are related with the code in the pull request?

Thanks!!
Eudaldo.

**Comment by kyle-miho** [comment]
looking into this rn

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
DDMFormFieldTypeSettingsEvaluatorTest.testSelectCallGetDataProviderInstanceOutputParameters2
and
DDMTemplateServiceTest.testSearchByName

Were the only 2 common failures among the two runs.
However I doubt that these tests are failing due to this pull because they do not involve journal-service at all.

The other failures are more likely to be flukes.

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66424. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
