### PR TITLE
LPS-89787 Filter and sort in categories

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/dgarciasarai/liferay-portal/pull/23. [See changes here.](https://github.com/ealonso/liferay-portal/compare/1070eeb7d3c5~2...1070eeb7d3c5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
