### PR TITLE
LPS-73070 Creates package-lock files (auto-generated)

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @ealonso, this change is in preparation to a global build update to node 8 and npm5 that to increase build speed and stability.

No need change the state of the LPS since I'm sending bits to every team and I'll manage it globally.

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51281. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
