### PR TITLE
LPS-86629 Baseline

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
cc:// @pavel-savinov

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64620. [See changes here.](https://github.com/ealonso/liferay-portal/compare/e8acc085e73b~1...e8acc085e73b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
