### PR TITLE
LPS-76137 Create configuration option for display style

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:retest

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53270. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53298. [See changes here.](https://github.com/ealonso/liferay-portal/compare/996798a~1...996798a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
