### PR TITLE
LPS-103793 buildLang

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80203. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80224. [See changes here.](https://github.com/ealonso/liferay-portal/compare/c86f887df74b~1...c86f887df74b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
