### PR TITLE
LPS-101401 Move the update code to a new model listener, as the structure is updated later in LayoutPageTemplateStructureRel service

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
@victorg1991 He pasado el último commit el primero no me convence, pq filtramos en unos métodos y en otros no?

**Pull request closed without merging**
