### PR TITLE
LPS-78661 Wait for the template handler registry activation to be sure that bundle context is available

### PR DESCRIPTION
**Pull request by kyle-miho**

### CODE REVIEW

**Comment by kyle-miho** [comment]
'/cc <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kyle-miho** [comment]
@ealonso @pavel-savinov I tested this ~5 times, I am pretty confident that this fix works given that Pavel also has been consistently unable to reproduce the bug now.

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:reopen

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61475. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
