### PR TITLE
LPS-78963 Drag handler

### PR DESCRIPTION
**Pull request by p2kmgcl**
/cc @pavel-savinov

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56376. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56380. [See changes here.](https://github.com/ealonso/liferay-portal/compare/1f106f5eaaaa~1...1f106f5eaaaa) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56381. [See changes here.](https://github.com/ealonso/liferay-portal/compare/af441d7e1e60~1...af441d7e1e60) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
