### PR TITLE
LPS-107564 Add unit tests for AnalyticsReportsDisplayContext

### PR DESCRIPTION
**Pull request by darquesdev**
@dgarciasarai

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
Pull request submitted https://github.com/ealonso/liferay-portal/pull/2746

**Pull request closed without merging**
