### PR TITLE
[TECHNICAL SUPPORT] LPS-105279 Avoid NullPointerException if there is no default name attributed to SiteNavigationMenuItem

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant tickets:
https://issues.liferay.com/browse/LPS-105279

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
The unique failure doesn't seem to be related to this issue.

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
sent here: https://github.com/brianchandotcom/liferay-portal/pull/81630

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
