### PR TITLE
LPS-76829 Buildlang

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54125. [See changes here.](https://github.com/ealonso/liferay-portal/compare/a1740b7~7...a1740b7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54128. [See changes here.](https://github.com/ealonso/liferay-portal/compare/36faf9f~8...36faf9f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54131. [See changes here.](https://github.com/ealonso/liferay-portal/compare/24d2cd3~8...24d2cd3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54150. [See changes here.](https://github.com/ealonso/liferay-portal/compare/bcd262d~8...bcd262d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
