### PR TITLE
LPS-73680 Delete old category properties only in case when new category properties array is not null

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
cc @jkappler

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50403. [See changes here.](https://github.com/ealonso/liferay-portal/compare/f45777b~2...f45777b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
