### PR TITLE
LPS-75321

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LPS-75321

### CODE REVIEW

**Comment by anthony-chu** [comment]
hi @ealonso, i've tried to resolve as many of the test failures as possible; however, i'm running into a few questions:

- how would a user navigate to the staged view if no pages are available? it looks like the staging toggle has been removed from the Navigation panel
- speaking of changes to the Navigation panel, there is no longer a "Go to Site" link in that panel. is that intentional?
- how do users navigate to private pages? will it only be through either (1) the private site friendlyURL or (2) the link in the Site Pages portlet?

thanks!

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/anthony-chu/liferay-portal/pull/256

**Pull request closed without merging**
