### PR TITLE
LPS-81675 Brings html2canvas as a dependency

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
Oh wait, maybe the PR tester isn't enabled for Eudaldo. Nevermind!

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/189. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
