### PR TITLE
LPS-130057

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@ealonso @ricardocousolr 

for

```
	public int getLayoutsCount(
			long groupId, String keywords, int[] statuses, String[] types)
		throws PortalException {
```

can you change it to

	public int getLayoutsCount(
			long groupId, String keywords, String[] types, int[] statuses)
		throws PortalException {

I'm assuming "String type' here is the same "type" column in Layout? If so, Layout#type goes before Layout#status in service builder.

Please apply the same pattern to your changes here so that type goes before status. Thx.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/4684. [See changes here.](https://github.com/ealonso/liferay-portal/compare/f73ec7bd25d1~3...f73ec7bd25d1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/4705. [See changes here.](https://github.com/ealonso/liferay-portal/compare/7dd7d955ee5b~3...7dd7d955ee5b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/4721. [See changes here.](https://github.com/ealonso/liferay-portal/compare/0b2e10e2bf83~4...0b2e10e2bf83) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
