### PR TITLE
LPS-75073 Simulation panel does not display on IE11 or Edge

### PR DESCRIPTION
**Pull request by dustinryerson**
Hey @ealonso,

This is an update for https://issues.liferay.com/browse/LPS-75073. The bug is closely related to https://issues.liferay.com/browse/LPS-73789, which was merged here: https://github.com/brianchandotcom/liferay-portal/pull/51449

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @p2kmgcl

**Comment by dustinryerson** [comment]
ci:reopen

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/p2kmgcl/liferay-portal/pull/22. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
