### PR TITLE
[TECHNICAL-SUPPORT] LPS-74236

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @mbowerman

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:reopen

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @mbowerman,

Do you know if we are going to have the same issue with HIGHEST_RATED_ASSETS, MOST_VIEWED_ASSETS and RECENT_CONTENT portlets?

Regards,
Eudaldo.

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51063. [See changes here.](https://github.com/ealonso/liferay-portal/compare/62d5794~1...62d5794) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51068. [See changes here.](https://github.com/ealonso/liferay-portal/compare/da39431~1...da39431) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
