### PR TITLE
[TS] LPS-111679

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/209. [See changes here.](https://github.com/ealonso/liferay-portal/compare/c7d0fb82983f~1...c7d0fb82983f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
