### PR TITLE
[TECHNICAL-SUPPORT] LPS-101550

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @holatuwol

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78393. [See changes here.](https://github.com/ealonso/liferay-portal/compare/54afc429a65e~1...54afc429a65e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
