### PR TITLE
[TECHNICAL-SUPPORT] LPS-95817

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
@jonathanmccann, @ealonso is ooo for a couple of days, so I took over. Sent to BChan here: https://github.com/brianchandotcom/liferay-portal/pull/76556

**Comment by jkappler** [comment]
ci:close

**Comment by jonathanmccann** [comment]
@jkappler Thank you for taking a look at this pull.

**Pull request closed without merging**
