### PR TITLE
LPS-79643 Buildlang

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57340. [See changes here.](https://github.com/ealonso/liferay-portal/compare/73a9e020477b~21...73a9e020477b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
