### PR TITLE
LPS-78208-TEMP Test button for the fragment item selector

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by psavinov** [comment]
ci:test

**Comment by pavel-savinov** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55690. [See changes here.](https://github.com/ealonso/liferay-portal/compare/4f8c9bf81d32~15...4f8c9bf81d32) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55691. [See changes here.](https://github.com/ealonso/liferay-portal/compare/b2f045130c80~15...b2f045130c80) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55744. [See changes here.](https://github.com/ealonso/liferay-portal/compare/2b8b39158e70~20...2b8b39158e70) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
