### PR TITLE
LPS-75544 Contextual sidebar

### PR DESCRIPTION
**Pull request by p2kmgcl**
/cc @jbalsas

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54506. [See changes here.](https://github.com/ealonso/liferay-portal/compare/1f41551~1...1f41551) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54532. [See changes here.](https://github.com/ealonso/liferay-portal/compare/8ba48b7~3...8ba48b7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
