### PR TITLE
LPS-100140 SF

### PR DESCRIPTION
**Pull request by jbalsas**
Previous test runs:

[❌ ci:test:stable - 7 out of 8 jobs passed](https://github.com/jbalsas/liferay-portal/pull/2031#issuecomment-553133780)
[❌ ci:test:relevant - 102 out of 113 jobs passed](https://github.com/jbalsas/liferay-portal/pull/2031#issuecomment-553133780)
[❌ci:test:default - 193 out of 229 jobs passed](https://github.com/jbalsas/liferay-portal/pull/2031#issuecomment-553152861)

> Reviewed. Test failures are unrelated. ✔️

This should also fix https://issues.liferay.com/browse/LPS-104512

/cc @john-co, @pavel-savinov, @adolfopa

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80929. [See changes here.](https://github.com/ealonso/liferay-portal/compare/8acfd230d791~12...8acfd230d791) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80930. [See changes here.](https://github.com/ealonso/liferay-portal/compare/0f321c90dc6f~12...0f321c90dc6f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80933. [See changes here.](https://github.com/ealonso/liferay-portal/compare/2c80173f12cc~12...2c80173f12cc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80934. [See changes here.](https://github.com/ealonso/liferay-portal/compare/4ec294b73b1f~12...4ec294b73b1f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
