### PR TITLE
LPS-98893 Do not destructure if not needed

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by victorg1991** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76290. [See changes here.](https://github.com/ealonso/liferay-portal/compare/c5bf5ed38732~15...c5bf5ed38732) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76315. [See changes here.](https://github.com/ealonso/liferay-portal/compare/7f3eb523d843~17...7f3eb523d843) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
