### PR TITLE
LPS-101058 As a site admin it should be possible to create content sets based on keyword searches

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by rotty3000** [comment]
@ealonso while the above is functional there is a coupld of details that I think can still use some work:

- the `_mergeKeywords` logic I think is not solid enough, might need assistance from @arboliveira to get it correct
- detecting and handling `luceneSyntax` could be cleaner

**Comment by rotty3000** [comment]
ci:stop

**Comment by rotty3000** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @rotty3000,

After reviewing your pull, I've see some improvements that we should take into account to merge it into the product.

- Move the _mergeKeywords to AssetSearcher, implementing it with BooleanFilter
- Implement something similar to addSearchAssetTagNames, creating new methods for all, any, notall and notany and maybe a new method for addSearchAssetKeywords
- Avoid using the "search.lucene.syntax" into the service context, I think we can avoid it if we create the new methods

Could you please take a look at it? if you don't have enough time, I can take care of it but I don't have enough time at this moment, so it should wait a couple of days.

Regards,
Eudaldo.

cc: @jorgeFerrer

**Comment by rotty3000** [comment]
hey @ealonso please see updated. I think this probably covers your comments.

**Comment by rotty3000** [comment]
Oh, and I also reflected the changes directly in the Asset Publisher portlet as well. So the logic in both places where the Filter builder is used are the same.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1100. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79223. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79274. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79276. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
