### PR TITLE
LPS-92606 Remove unused

### PR DESCRIPTION
**Pull request by epgarcia**
Hi @ealonso, 

This PR replaces the ScreenNavigation pattern in asset lists with the FormNavigation pattern, as in Asset Publisher.

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/epgarcia/liferay-portal/pull/732. [See changes here.](https://github.com/ealonso/liferay-portal/compare/ffd5ed62c73c~8...ffd5ed62c73c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
