### PR TITLE
LPS-107151 As a site admin, I want to assign site roles to site-level segments

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-107151](https://issues.liferay.com/browse/LPS-107151).<br><br>Hey @ealonso, I originally sent this to Eduardo Garcia, but I forgot that he was on sabbatical. Would you mind looking over the changes to the Segments modules? The goal is to allow assigning site roles to segments inside of the Segments portlet. Let me know if you have any questions. Thanks!<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
Original PR to Eduardo: https://github.com/epgarcia/liferay-portal/pull/1009

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
cc: @cgoncas @darquesdev @dgarciasarai

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Retrying. The test failure happens in other pulls as well.

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Sorry about this one guys, A poshi workaround was just push to BChan to avoid most of this failures on the Poshi side.. Unfortunately the Duplicate Entry error on the integration test will be difficult to add a temp ignore and is a race condition. Going to try one more time.

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/cgoncas/liferay-portal/pull/452. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
