### PR TITLE
LPS-91917 Fix content scripts running twice

### PR DESCRIPTION
**Pull request by phcp**
Please see https://issues.liferay.com/browse/LPS-91917.

Thanks!

### CODE REVIEW

**Comment by phcp** [comment]
ci:test:sf

**Comment by phcp** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/p2kmgcl/liferay-portal/pull/382. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
