### PR TITLE
[TECHNICAL-SUPPORT] LPS-75793

### PR DESCRIPTION
**Pull request by jonathanmccann**
From @mbowerman 

>With this fix, if you have an inactive site that has an active child site, neither the parent nor child will be displayed. I thought this behavior made more sense than displaying the child site unattached to its parent. Also, the same behavior already exists if you have a site without layouts that has a child site with layouts.

>I thought we should fix it in the GroupFinder, rather than in page.jsp, because the GroupFinder method seems like it is supposed to be used to find sites whose layouts can be visited, so inactive sites should not be returned by it. Everything I could find that called this method seemed like it would benefit from not returning inactive sites.

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:reopen

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53087. [See changes here.](https://github.com/ealonso/liferay-portal/compare/d5554aa~6...d5554aa) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53088. [See changes here.](https://github.com/ealonso/liferay-portal/compare/e4a4dc6~8...e4a4dc6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53131. [See changes here.](https://github.com/ealonso/liferay-portal/compare/b794d6c~8...b794d6c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53193. [See changes here.](https://github.com/ealonso/liferay-portal/compare/3b90bcd~7...3b90bcd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
