### PR TITLE
LPS-78956 Fix integration tests due to the property name change

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by stsquared99** [comment]
ci:help

**Comment by stsquared99** [comment]
ci:test:sf

**Comment by ealonso** [comment]
@stsquared99 @pyoo47, 

Hey guys I've added liferay-continuous-integration as collaborator, Could you please accept the invitation? https://github.com/ealonso/liferay-portal/invitations

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56419. [See changes here.](https://github.com/ealonso/liferay-portal/compare/82f8fa4544f5~2...82f8fa4544f5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
