### PR TITLE
LPS-120383

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/94267

**Comment by brianchandotcom** [comment]
@ealonso please send me a follow up pull if my logic is good.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/2354. [See changes here.](https://github.com/ealonso/liferay-portal/compare/44750d741a72~1...44750d741a72) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
