### PR TITLE
[TECHNICAL-SUPPORT] LPS-78167 SF

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-78167

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:test

**Comment by JosemariaMunoz** [comment]
ci:retest

**Comment by JosemariaMunoz** [comment]
ci:test

**Comment by JosemariaMunoz** [comment]
Hi @ealonso ,

PR Testing is not working but I tried before on my own account and I think failures are not related to this change: https://github.com/JosemariaMunoz/liferay-portal/pull/23

Thanks!

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56365. [See changes here.](https://github.com/ealonso/liferay-portal/compare/d36cb789e103~3...d36cb789e103) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
