### PR TITLE
LPS-101337 Update usages

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78187. [See changes here.](https://github.com/ealonso/liferay-portal/compare/690349886363~1...690349886363) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
