### PR TITLE
LPS-135841 add staging

### PR DESCRIPTION
**Pull request by lfbesada**

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/5299. [See changes here.](https://github.com/ealonso/liferay-portal/compare/e4391cf3ff75~2...e4391cf3ff75) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
