### PR TITLE
[TECHNICAL SUPPORT] LPS-98890 Don't use default locale (en_US) in case language_id is not valid

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-98890

This is problematic in case a customer upgrades from 6.1 and older versions and customer ends with invalid language-id values, but it can also reproduced in case you do some changes in locale configuration

Reviewed with @dacousalr

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76283. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
