### PR TITLE
LPS-100139, LPS-100144 React tag components in asset-taglib and document-library

### PR DESCRIPTION
**Pull request by wincent**
Previously reviewed at:

- https://github.com/jbalsas/liferay-portal/pull/1960
- https://github.com/jbalsas/liferay-portal/pull/1970
- https://github.com/jbalsas/liferay-portal/pull/1973
- https://github.com/wincent/liferay-portal/pull/72
- https://github.com/wincent/liferay-portal/pull/74

### CODE REVIEW

**Comment by wincent** [comment]
@ealonso: @jbalsas suggested I forward this on to you — it's some React rewrites of asset tag selector components in asset-taglib and document-library-web done by @carloslancha and @julien.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/ambrinchaudhary/liferay-portal/pull/259. [See changes here.](https://github.com/ealonso/liferay-portal/compare/c758bd56848d~4...c758bd56848d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
