### PR TITLE
LPS-64197 get refresh window id from request

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38169. [See changes here.](https://github.com/ealonso/liferay-portal/compare/278c557~3...278c557) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/686. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
