### PR TITLE
LPS-118325 Publish to Live fails at the second time with category

### PR DESCRIPTION
**Pull request by moltam89**

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test

**Comment by moltam89** [comment]
ci:test

**Comment by moltam89** [comment]
ci:retest

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
resend here: https://github.com/liferay-echo/liferay-portal/pull/1855

**Pull request closed without merging**
