### PR TITLE
[TECHNICAL-SUPPORT] LPS-87081

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
sent here: https://github.com/brianchandotcom/liferay-portal/pull/64902

**Pull request closed without merging**
