### PR TITLE
LPS-75321 privacy parameter needed when viewing page

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
Hey @anthony-chu,

Could you please take a look at CPPagetemplates#AddSitePageTemplate? I think is the only real broken test. I've tried to fix it by myself but I couldn't.

Thanks!!
Eudaldo.

**Comment by anthony-chu** [comment]
hi @ealonso, i'll try and take a look at it today. thanks!

**Comment by anthony-chu** [comment]
resent here: https://github.com/ealonso/liferay-portal/pull/1225

**Pull request closed without merging**
