### PR TITLE
LPS-96691 Use constants from Segments API module

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
ci:test:relevant <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75188. [See changes here.](https://github.com/ealonso/liferay-portal/compare/5092ec947381~8...5092ec947381) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75189. [See changes here.](https://github.com/ealonso/liferay-portal/compare/2616437837ba~9...2616437837ba) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
