### PR TITLE
LPS-80313 Use portletResource from the request if exists since we allow page creation from different portlets

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
The same as https://github.com/ealonso/liferay-portal/pull/1609. Still reproducible on master.

**Comment by pavel-savinov** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57960. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
