### PR TITLE
[TECHNICAL-SUPPORT] LPS-87005

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Hi @jonathanmccann, this has conflicts with https://github.com/brianchandotcom/liferay-portal/pull/65001 so I'll send it once the other is merged

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Hi @jonathanmccann, I was checking this today, and the issue is solved with the first commit. Do we need to change service for local service in the asset render factories?

Let me know and I'll send the PR later on to BChan

**Comment by jonathanmccann** [comment]
If we leave out the second commit then we'll be checking the permissions twice unnecessarily, the rest of the files also use the *LocalService, and finally the PrincipalException will be thrown in a place where it will be extremely difficult to catch and display to the user.

See https://issues.liferay.com/browse/LPP-32077 for more details on the last reasoning.

**Comment by jkappler** [comment]
Thanks for the clarification @jonathanmccann!! PR sent here: https://github.com/brianchandotcom/liferay-portal/pull/65047

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
