### PR TITLE
LPS-105952 Delete specific converters, since they are superseded by DefaultLayoutConverter

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/ruben-pulido/liferay-portal/pull/154. [See changes here.](https://github.com/ealonso/liferay-portal/compare/471dd277227d~4...471dd277227d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
