### PR TITLE
LPS-107109 Call thunk to update allowed fragment entry links

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83601. [See changes here.](https://github.com/ealonso/liferay-portal/compare/196ebaa8e781~2...196ebaa8e781) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
