### PR TITLE
LPS-78016 Buildlang

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56316. [See changes here.](https://github.com/ealonso/liferay-portal/compare/257e078e96ac~13...257e078e96ac) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56329. [See changes here.](https://github.com/ealonso/liferay-portal/compare/dc7fb2b32553~13...dc7fb2b32553) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
