### PR TITLE
LPS-76845 When updating the entry, remove first the related categories, and readd if they come in the method

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by jkappler** [comment]
ci:retest

**Comment by jkappler** [comment]
ci:test

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55295. [See changes here.](https://github.com/ealonso/liferay-portal/compare/7b99aca9b376~3...7b99aca9b376) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
