### PR TITLE
[TECHNICAL-SUPPORT] LPS-69799

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
Resend: https://github.com/ealonso/liferay-portal/pull/768

**Pull request closed without merging**
