### PR TITLE
[TECHNICAL-SUPPORT] LPS-96238

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-96238

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:test:sf

**Comment by JosemariaMunoz** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73886. [See changes here.](https://github.com/ealonso/liferay-portal/compare/29a41ce91db2~2...29a41ce91db2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73897. [See changes here.](https://github.com/ealonso/liferay-portal/compare/43e41d8c9dde~1...43e41d8c9dde) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
