### PR TITLE
LPS-114454 and LPS-114455: Implement FormProvider for JournalArticle and BlogsEntry

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:test

**Comment by JorgeFerrer** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
https://github.com/jorgeFerrer/liferay-portal/pull/878

**Pull request closed without merging**
