### PR TITLE
[TECHNICAL-SUPPORT] LPS-72155

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @jonathanmccann @thomasstew 

thanks a lot for fixing this issue. I just have a question regarding the solution... what would happen now when a user has recen sites but doesn't have any site to be shown under my sites? I tend to think those two tabs are always shown now.... 
The logic for that is in the MySitesItemSelectorView and RecentSitesItemSelectorView, method isVisible.
What do you think?

Thank you!

**Comment by thomasstew** [comment]
Hi @juliocamarero 

Currently both tabs are always displayed, but My Sites may or may not be populated. 
screenshot from 2017-05-10 09-42-49

The isVisible method always returns true for both -ItemSelectorView classes. Are you suggesting we implement logic to only display a tab if it has sites to display?

**Comment by juliocamarero** [comment]
@thomasstew I was not sure... just thinking outloud. It is probably ok as it is now, it looks good in your screenshot.  👍  thank you!

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/48950. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
