### PR TITLE
LPS-98244 Remove unnecessary margin

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75764. [See changes here.](https://github.com/ealonso/liferay-portal/compare/c56db5399e4b~2...c56db5399e4b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
