### PR TITLE
LPS-80132 buildLang

### PR DESCRIPTION
**Pull request by matethurzo**
Hey @ealonso this is a customer issue.

It's quite complicated but the main problem here is the following:
1) if staging is turned on for an asset (ie.: web content)
2) and turned off for a different asset (ie.: bookmarks)
3) it does matter if you are linking them together from bookmarks or web content. 
4) if you are linking them from bookmarks, it means the link will be created in live (wc's asset group id will be live)
5) if you are linking from web content it mean the link will be created in stage (wc's asset group id will be stage)

This is the basic problem. A support solution provided a fix but caused other regressions, so I think the best approach in this case is:
1) if one end of the relationship is staged, we should only allow linking from there. 
2) if both staged, it's allowed from both end
3) if both live, it's allowed from both end

The solution itself is simple. please let me know what do you think.

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test:sf

**Comment by matethurzo** [comment]
ci:test:relevant

**Comment by matethurzo** [comment]
ci:reopen

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60576. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
