### PR TITLE
LPS-76967 Call the template to render the already added fragments

### PR DESCRIPTION
**Pull request by jkappler**
@ealonso, la PR de la que dependíamos ya se ha mergeado. Es la LPS-77196

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54746. [See changes here.](https://github.com/ealonso/liferay-portal/compare/93511f1~2...93511f1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54747. [See changes here.](https://github.com/ealonso/liferay-portal/compare/a933633~2...a933633) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
