### PR TITLE
LPS-100134

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81087. [See changes here.](https://github.com/ealonso/liferay-portal/compare/111725f9d288~1...111725f9d288) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
