### PR TITLE
LPS-93312 Fix tooltip message in sorting buttons

### PR DESCRIPTION
**Pull request by dgarciasarai**
https://github.com/dgarciasarai/liferay-portal/pull/45

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70731. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
