### PR TITLE
J cords lps 104398 rebased 2

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-104398

cc @chriskian

Resent from: https://github.com/ealonso/liferay-portal/pull/2630

I put the method into the JournalUtil. I also made sure article.getFolder() was inside trys. getFolder() should either throw an exception or [return a folder](https://github.com/liferay/liferay-portal/blob/ffbfff2673f2ada7c16f021ede1caa0562de7280/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/model/impl/JournalArticleImpl.java#L345-L347).

Let me know any specific changes still needed.

> Problem: Notifications for Web Content always directed users to the root folder (of the staging site if local staging).
> 
> Solution: Proposed here https://liferay.slack.com/archives/CMFC54M1N/p1573508487009900 have the Notification redirect to the article's direct folder (and to the article's site if staging).
> 
> Most of the complication was in the JournalArticleStagedModelDataHandler where we need to update the notification to contain the proper URLs in the case of having a subscriber on a Live site in Local Staging. There's no Liferay utilities to help us, so it is almost completely manual manipulation. Similarly, in the getFolderURLViewInContext(), manipulating the URL in the case of staging is manual. I kept the liferayPortletResponse as the primary way to generate the URL. It's preferred because that URL will contain the p_p_auth token id which we have no access to without the Response.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @joshuacords,

I have a question, Why we use the [$ARTICLE_URL$] as String in JournalArticleLocalServiceImpl and we use the [$ARTICLE_URL$] as Map in JournalArticleStagedModelDataHandler?

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/joshuacords/liferay-portal/pull/59. [See changes here.](https://github.com/ealonso/liferay-portal/compare/f66e7c51d42b~8...f66e7c51d42b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by joshuacords** [comment]
> Hey @joshuacords,
> 
> I have a question, Why we use the [$ARTICLE_URL$] as String in JournalArticleLocalServiceImpl and we use the [$ARTICLE_URL$] as Map in JournalArticleStagedModelDataHandler?

Hi @ealonso,

I'm assuming you're referring to this code in JournalArticleLocalServiceImpl: https://github.com/liferay/liferay-portal/blob/e629922a0f12d168190a9c961c95d2ab728b65c2/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L8121

In this case the string is ultimately packed into a map by the SubscriptionSender here: https://github.com/liferay/liferay-portal/blob/3e1fdb7c7ed619751c6ed157a58e07b57380895c/portal-kernel/src/com/liferay/portal/kernel/util/SubscriptionSender.java#L355-L357

JournalArticleStagedModelDataHandler is repeating the same pattern.

**Pull request closed without merging**
