### PR TITLE
LPS-93065 Avoid using important

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
ci:close

**Comment by SamZiemer** [comment]
Hi @pavel-savinov,

Did this pull get forwarded anywhere? The LPS doesn't link to any other pull requests.

**Pull request closed without merging**
