### PR TITLE
LPS-91536

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/399. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
