### PR TITLE
LPS-105689 Uses new createPortletURL utility instead of old AUI one

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84326. [See changes here.](https://github.com/ealonso/liferay-portal/compare/2a8428a29add~2...2a8428a29add) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84383. [See changes here.](https://github.com/ealonso/liferay-portal/compare/4e7e6e0d3814~2...4e7e6e0d3814) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
