### PR TITLE
LPS-115840 Split FormProvider, moving methods to retrieve values to a new InfoItemValuesProvider service

### PR DESCRIPTION
**Pull request by JorgeFerrer**
@4lejandrito @adolfopa

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
@JorgeFerrer esto no compila

**Comment by JorgeFerrer** [comment]
🤦 Sorry about that. 
I had done "ant all" and "gradlew clean deploy" in the affected modules. I didn't know that either of them compile the integration tests :(
I've fixed it and added two more commits.

**Comment by JorgeFerrer** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
@JorgeFerrer Source Formatting error

**Comment by JorgeFerrer** [comment]
Resent as https://github.com/ealonso/liferay-portal/pull/3000

**Pull request closed without merging**
