### PR TITLE
[TS] LPS-108660 Use List<String> instead of String

### PR DESCRIPTION
**Pull request by balazssk**
Hi @ealonso ,

getSelectedCategories is only used in _getCategoriesJSONArray to match categoryIds to a csv with String#contains. I think that individually matching the current categoryId to the elements of a list is safer.

Can you please review?
https://issues.liferay.com/browse/LPS-108660

Thanks,
Balázs

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84658. [See changes here.](https://github.com/ealonso/liferay-portal/compare/0e5eee19a054~1...0e5eee19a054) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by yonyete** [comment]
@ealonso Hi, I'm the one who asked for this solution :)

This class also contains the same issue, in addition to the one you modified. Could you update the code there too, please?

com.liferay.asset.categories.selector.web.display.context.AssetCategoriesSelectorDisplayContext

**Comment by balazssk** [comment]
Hi @yonyete ,
com.liferay.asset.categories.selector.web.display.context.AssetCategoriesSelectorDisplayContext
was moved into 
com.liferay.asset.categories.selector.web.internal.display.context.AssetCategoriesSelectorDisplayContext
in https://issues.liferay.com/browse/LPS-94301

so they are the same file, you just found an older version

**Comment by yonyete** [comment]
Ok, thanks for the clarification @balazssk

**Pull request closed without merging**
