### PR TITLE
LPS-102749 When subscribing to a Live Site, use the defaultArticleURL…

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @joshuacords

Notes from Josh:
> https://issues.liferay.com/browse/LPS-102749
> https://issues.liferay.com/browse/LPP-35235
> 
> **Problem:** When notifications are sent out to live site subscribers in a staging environment, the liferayPortletRequest is null, this causes getURLViewInContext() to return "" which is later replaced with the notification portlet url instead of the appropriate Journal Article URL.
> 
> **Solution:** Use the defaultArticleURL which points to the correct portlet, if one can be created, in the above situation.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79185. [See changes here.](https://github.com/ealonso/liferay-portal/compare/b6c41fa87b4a~1...b6c41fa87b4a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
