### PR TITLE
LPS-79914 Redirect on cancel

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57470. [See changes here.](https://github.com/ealonso/liferay-portal/compare/ea976a1b62ac~3...ea976a1b62ac) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57473. [See changes here.](https://github.com/ealonso/liferay-portal/compare/e968492c26d1~3...e968492c26d1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
