### PR TITLE
LPS-79521

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hey @ealonso,

This one is interesting because we can't seem to find the best way to resolve it. I'll lay our thoughts here, please let us know what you think.

1. Fix the issue with this proposed fix. This fix looks rather hack-y and I'm not sure if it would behave strangely if we did an advanced search and entered the same term for the userName, title, and description.

2. Fix the issue by using the same `buildSearchContext` method that the `search` uses. The `searchCount` method uses https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/asset/service/impl/AssetEntryLocalServiceImpl.java#L1137 (which does not set the keywords) while the `search` method uses https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/asset/service/impl/AssetEntryLocalServiceImpl.java#L1121 (which does set the keywords). The issue with this approach is that it renders the userName, title, and description parameters useless since we only really need one.

3. Create a new method that takes in a keywords parameter instead of userName, title, and description or adds a new content parameter in addition to those three. I believe this is the best solution but it will cause a major version increase on portal-kernel. I'm not sure if that change would be accepted since we're close to release. If you're interested in this solution please see https://github.com/jonathanmccann/liferay-portal/pull/1605 for a possibility.

Thank you.

/cc @brianikim

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @brianikim @jonathanmccann,

I've followed the descriptions steps of the issue and I cannot reproduce the issue on master. please take a look at the screenshots:

welcome_-_liferay-2
welcome_-_liferay-3

Are there any additional steps? Do I miss something?

Regards,
Eudaldo.

**Comment by ealonso** [comment]
@jonathanmccann @brianikim 

Also all my contents have the same title, description and content.

**Comment by brianikim** [comment]
Hello @ealonso ,

Please let me know if you are still having trouble with reproducing the steps.

Sincerely,
Brian Kim

**Comment by ealonso** [comment]
Hey @brianikim ,

@dacousalr is taking a look at it, to check if this is the best solution for fixing the issue.

Regards,
Eudaldo.

**Comment by brianikim** [comment]
Hello @dacousalr ,

The change in the method JournalArticleAssetRenderer.getSummary is necessary because we need to shorten the content when the description column is using the content in web content display portlet. Otherwise, the web content display will try to display all of the contents however they may be long.

Sincerely,
Brian Kim

**Comment by dacousalr** [comment]
Thanks for the clarification, @brianikim,

Knowing that, I think that change should be done in another ticket.

In any case, please resend the solution based on approach 3.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/dacousalr/liferay-portal/pull/36. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
