### PR TITLE
[TS] LPS-110278

### PR DESCRIPTION
**Pull request by ChrisKian**
From @kevhlee:

> <https://issues.liferay.com/browse/LPS-110278>
> 
> When the parent of a content page layout is updated, the parent of the corresponding draft layout must also be updated. However, this was not the case. Thus, draft layouts would reference the wrong parent layouts (potentially deleted ones). The layout permission checker looks at the parent of each layout, including draft layouts, as seen in the following:
> 
> * <https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/permission/LayoutPermissionImpl.java#L268-L279>.
> 
> Because of this, the layout permission checker can potentially look for a deleted layout and throw a `NoSuchLayoutException`, which was causing the problem described in [LPS-110278](https://issues.liferay.com/browse/LPS-110278).
> 
> With regards,
> Kevin

CC @wanderlast

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
ci:close

**Comment by pavel-savinov** [comment]
Sent to Brian [here](https://github.com/brianchandotcom/liferay-portal/pull/86399)

**Pull request closed without merging**
