### PR TITLE
[TECHNICAL-SUPPORT] LPS-99967

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/jonathanmccann/liferay-portal/pull/1824. [See changes here.](https://github.com/ealonso/liferay-portal/compare/fc2fad0139f5~7...fc2fad0139f5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
