### PR TITLE
LPS-91810 Build lang

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70621. [See changes here.](https://github.com/ealonso/liferay-portal/compare/871f6c718f14~1...871f6c718f14) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
