### PR TITLE
LPS-72208 Fix the retrieval of the localization map for body and subject of email based on the preferences

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:retest

**Comment by jkappler** [comment]
ci:retest

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49046. [See changes here.](https://github.com/ealonso/liferay-portal/compare/0c7409f~1...0c7409f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
