### PR TITLE
LPS-72355 buildLang

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49239. [See changes here.](https://github.com/ealonso/liferay-portal/compare/1021d52~8...1021d52) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
