### PR TITLE
LPS-76921 Semantic versioning

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by pavel-savinov** [comment]
Los fallos son de com.liferay.portal.security.sso.ntlm(SF) y de AssetVocabulary, no tienen nada que ver con la pull.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54292. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
