### PR TITLE
[TECHNICAL-SUPPORT] LPS-76668

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by ealonso** [comment]
@jonathanmccann Could you please send this one to @matethurzo?

**Comment by jonathanmccann** [comment]
ci:stop

**Comment by jonathanmccann** [comment]
https://github.com/matethurzo/liferay-portal/pull/2090

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66781. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
