### PR TITLE
[TS] LPS-109833 If layoutTypePortlet.addPortletId returns null, throw a controlled PortalException

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-109833

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85813. [See changes here.](https://github.com/ealonso/liferay-portal/compare/53def5e90ffc~1...53def5e90ffc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
