### PR TITLE
LPS-76089 Instantiable for content

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Please check: https://github.com/ealonso/liferay-portal/pull/1448

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
