### PR TITLE
[TS] LPS-91603

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-91603

Hi Eudaldo,

According to [Zoltan's comment](https://issues.liferay.com/browse/LPS-78851?focusedCommentId=1276226&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1276226), a user should see sites appear in the "Recent" tab if it has a public page or the user is a site member and there is at least one private page.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69015. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
