### PR TITLE
LPS-77036 Fix sidebar fragments overflow

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
ci:test

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56175. [See changes here.](https://github.com/ealonso/liferay-portal/compare/0ce9d14dcf68~2...0ce9d14dcf68) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
