### PR TITLE
LPS-78099 Apply fragments editor when editing a page so that the user can edit the text in fragments that are editable

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
@jkappler el classNameId no es necesario para que lo añades?

**Comment by jkappler** [comment]
@ealonso, se va a usar para el render. Lo podemos quitar y agregar en la siguiente PR

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55520. [See changes here.](https://github.com/ealonso/liferay-portal/compare/e440e56246c6~8...e440e56246c6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
