### PR TITLE
LPS-109788 Add info traces to LayoutTypePortletImpl.addPortletId in every "return null;"

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-109788

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85811. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
