### PR TITLE
[TECHNICAL-SUPPORT] LPS-78430

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @brianikim

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by brianikim** [comment]
hello @ealonso,

any updates on this PR?
Please let me know if anything is wrong or needs more fixing. Thanks.

Sincerely,
Brian Kim

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/153. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
