### PR TITLE
LPS-73018 When using a custom layout template that has div ids not prefixed with "column-", any portlets in that div no longer display after upgrading to DXP

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:reopen

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/1005. [See changes here.](https://github.com/ealonso/liferay-portal/compare/f3a8cdd~3...f3a8cdd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49907. [See changes here.](https://github.com/ealonso/liferay-portal/compare/714f4cd~1...714f4cd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
