### PR TITLE
[TECHNICAL-SUPPORT] LPS-74870

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @gregory-bretall

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Hey guys. After following the steps, I cannot select the spanish language. I set the virtual host to: www.able.com and then create a page called "a" (the only difference from the steps in the ticket). But in the language portlet, the spanish flag has this url:

http://www.able.com:8080/c/portspanishl/updspanishte_lspanishnguspanishge?p_l_id=40609&redirect=%2Fspanish&languageId=es_ES

I don't know if it's related to the changes. But the URL is updating incorrectly

**Comment by gregory-bretall** [comment]
Hi @jkappler I think that is likely an issue with my change. I can work on resolving the issue. Feel free to close the PR and I'll resend it once the issue is fixed. Apologies for the problem.

**Pull request closed without merging**
