### PR TITLE
Lps 106205 locked experiences

### PR DESCRIPTION
**Pull request by andresfulla**
Comes with the extra commit https://github.com/ealonso/liferay-portal/commit/16b58ba8bc9d427c1aef39ed09c2183ee657290d

cc/ @p2kmgcl

### CODE REVIEW

**Comment by andresfulla** [comment]
ci:test:sf

**Comment by andresfulla** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/victorg1991/liferay-portal/pull/173. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
