### PR TITLE
document-selector-109995

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Comment by jpince** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2858. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
