### PR TITLE
[Technical Support] LPS-74263 | master

### PR DESCRIPTION
**Pull request by samanzanedo**
https://issues.liferay.com/browse/LPS-74263

Thanks!

### CODE REVIEW

**Comment by samanzanedo** [comment]
ci:reopen

**Comment by samanzanedo** [comment]
ci:retest

**Comment by samanzanedo** [comment]
ci:reopen

**Comment by samanzanedo** [comment]
ci:retest

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51165. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
