### PR TITLE
LPS-69860 build-lang

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by ealonso** [comment]
Please use the Google Map API key defined on Site Settings

site_settings_-_liferay

Thanks!!!

**Pull request closed without merging**
