### PR TITLE
master-qa-19774

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-19774

### CODE REVIEW

**Comment by brianwulbern** [comment]
@ealonso 

Not sure what happened in your pull, but I tested that failing Poshi test locally on this branch and it passed.

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
Case in point ^, something's up with the pr-tester. :)

**Comment by ealonso** [comment]
Hey @brianwulbern,

All this code is already on master, hehe.

Thanks you very much!!!

**Comment by brianwulbern** [comment]
Oh, haha, last I saw, BChan wanted it [fixed](https://github.com/brianchandotcom/liferay-portal/pull/32674#issuecomment-159989693), and I didn't see any other pulls than these two:
https://github.com/brianchandotcom/liferay-portal/pull/32670
https://github.com/brianchandotcom/liferay-portal/pull/32663

**Pull request closed without merging**
