### PR TITLE
LPS-79976 Fix ignored line number

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57463. [See changes here.](https://github.com/ealonso/liferay-portal/compare/867532ba8951~1...867532ba8951) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57518. [See changes here.](https://github.com/ealonso/liferay-portal/compare/44076e5ce114~1...44076e5ce114) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
