### PR TITLE
LPS-85948 Remove the option to "Link Application URLs to Page" from Look and Feel Configuration Widget

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
@dacousalr

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65925. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
