### PR TITLE
LPS-89575 Segmented fragments in Pages

### PR DESCRIPTION
**Pull request by darquesdev**
@epgarcia @andresfulla

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67810. [See changes here.](https://github.com/ealonso/liferay-portal/compare/d9cbd2310035~2...d9cbd2310035) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67811. [See changes here.](https://github.com/ealonso/liferay-portal/compare/dd887b134cb0~2...dd887b134cb0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
