### PR TITLE
LPS 61890

### PR DESCRIPTION
**Pull request by marcoscv-work**
@ealonso You can change the style as far as you need

cc /@juliocamarero

### CODE REVIEW

**Comment by marcoscv-work** [comment]
no_results

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/juliocamarero/liferay-portal/pull/3894. [See changes here.](https://github.com/ealonso/liferay-portal/compare/e372ed1~3...e372ed1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2856. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2857. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
