### PR TITLE
LPS-84583 Use new method on workflow task

### PR DESCRIPTION
**Pull request by pedroqueiroz**
Hi @ealonso ,

I'm not sure if you are the right person to review this PR, so please, let me know if I should've sent to anyone else.

Thanks in advance! :)

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci: test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63497. [See changes here.](https://github.com/ealonso/liferay-portal/compare/2e1258ce9c3a~2...2e1258ce9c3a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
