### PR TITLE
LPS-79878 Remove verifyJournal: moving logic to the proper upgrade process or deleting the useless one

### PR DESCRIPTION
**Pull request by achaparro**
Hi @ealonso,

This pull removes the verifyJournal moving the useful logic to the proper upgrade process.

I have tested the changes with several upgrades from 6.1.20 with the proper data.

Could you check it tomorrow? I know that this is in a bit of a hurry but QA is going to start testing upgrade processes and we need to freeze the code.

Thanks!
cc/ @jkappler, @pavel-savinov @Preston-Crary

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test

**Comment by achaparro** [comment]
tests seem unrelated, similar to: https://github.com/ealonso/liferay-portal/pull/1650

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/58043. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
