### PR TITLE
LPS-72641 SF

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by p2kmgcl** [comment]
ci:retest

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
ci:retest

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/753. [See changes here.](https://github.com/ealonso/liferay-portal/compare/1752647~1...1752647) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
