### PR TITLE
[TECHNICAL-SUPPORT] LPS-57732 Search portlet ignores the label defined in the Facet Configuration

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-57732

You can find screenshots about the updated view on the ticket as well as a link to the related forum thread: https://issues.liferay.com/browse/LPS-57732?focusedCommentId=650672&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-650672

Cheers,
Tibor

/cc @juliocamarero

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Hey @lipusz 

after your changes the configuration in master looks very weird. We probably need a facet name and a facet label...

what do you think?

welcome_-_liferay 2

**Comment by lipusz** [comment]
We may need to override the "getTitle" in each Facet and return a different key. Make sense?

**Comment by lipusz** [comment]
Anyway, I have not had the chance to a take a further look at this yet (still building master), I don't understand why my changes have effect on the config view: in facet_configuration.jsp it uses the "className" of the searchFacet as a 'name' for the input not the 'label':

````jsp
SearchFacet searchFacet = (SearchFacet)request.getAttribute("facet_configuration.jsp-searchFacet");
%>

<aui:fieldset>
	<aui:input label="display-facet" name='<%= searchFacet.getClassName() + "displayFacet" %>' type="checkbox" value="<%= !searchFacet.isStatic() %>" />

	<div class="facet-configuration-options" id="<portlet:namespace /><%= AUIUtil.normalizeId(searchFacet.getClassName()) %>Options">
		<aui:input label="weight" name='<%= searchFacet.getClassName() + "weight" %>' value="<%= searchFacet.getWeight() %>" />

		<%
		searchFacet.includeConfiguration(request, response);
		%>

	</div>
</aui:fieldset>

<aui:script>
	Liferay.Util.toggleBoxes('<portlet:namespace /><%= AUIUtil.normalizeId(searchFacet.getClassName()) %>displayFacet', '<portlet:namespace /><%= AUIUtil.normalizeId(searchFacet.getClassName()) %>Options');
</aui:script>
````

**Comment by lipusz** [comment]
OK, I've figured it out: it's in display_settings.jspf:

````jsp
<aui:input label="<%= searchFacet.getTitle() %>" name='<%= "preferences--" + searchFacet.getClassName() + "--" %>' type="checkbox" value="<%= searchDisplayContext.isDisplayFacet(searchFacet.getClassName()) %>" />
...
````

**Comment by lipusz** [comment]
I'll update the facets to return a title instead of the label

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi @juliocamarero 

Added @6790cf5ad8d7a71a16c1305912ebb2f112f95310 to keep the current config view.

Also rebased to latest master.

Thx,
Tibor

**Comment by lipusz** [comment]
Rebased.

**Comment by juliocamarero** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/29259

Thanks a lot!! :+1:

**Pull request closed without merging**
