### PR TITLE
Lps 82433

### PR DESCRIPTION
**Pull request by eperezg**

### CODE REVIEW

**Comment by eperezg** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@ealonso I hope you don't mind, I'm going to push this to Brian since it looks like it will resolve a lot of failures in modules-integration. See results in https://github.com/brianchandotcom/liferay-portal/pull/60541#issuecomment-398845845

**Comment by jpince** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60554. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
ci:close

**Pull request closed without merging**
