### PR TITLE
LPS-78408 Build Lang

### PR DESCRIPTION
**Pull request by jkappler**
@ealonso, this was developed on top of https://github.com/ealonso/liferay-portal/pull/1477, so we have to pass that first

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55809. [See changes here.](https://github.com/ealonso/liferay-portal/compare/3901651ee86f~7...3901651ee86f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55826. [See changes here.](https://github.com/ealonso/liferay-portal/compare/5231ea573462~6...5231ea573462) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55834. [See changes here.](https://github.com/ealonso/liferay-portal/compare/28370bd68d40~7...28370bd68d40) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
