### PR TITLE
LPS-37310

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @ealonso,

Attached is an update for http://issues.liferay.com/browse/LPS-37310.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jkappler** [comment]
Hi @jonmak08, @ealonso is out of office.  Just one question, isn't this more of a collaboration issue than an WEM issue?

Thanks

**Comment by jonmak08** [comment]
Hey @jkappler,

It is a collaboration issue since it deals with the wiki portlet, but I looked at the history of the wiki portlet and saw that @ealonso was a part of those reviews.  Should I send this to @ambrinchaudhary instead?

Please let me know if you have any questions. Thanks!

**Comment by jkappler** [comment]
Hi @jonmak08, I think it would be better to send it to her

**Comment by jonmak08** [comment]
Ok.  I will send it to @ambrinchaudhary instead.  Thanks for the update @jkappler!

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/ambrinchaudhary/liferay-portal/issues/168

**Pull request closed without merging**
