### PR TITLE
LPS-90654 Fix test

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68188. [See changes here.](https://github.com/ealonso/liferay-portal/compare/3bbf7e8e4cae~1...3bbf7e8e4cae) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68190. [See changes here.](https://github.com/ealonso/liferay-portal/compare/bf6ae556eef1~1...bf6ae556eef1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
