### PR TITLE
LPS-109428 Remove not relevant test

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by david-gutierrez-mesa** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85495. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
