### PR TITLE
[TECHNICAL-SUPPORT] LPS-92995

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @SpencerWoo 

Notes from Spencer:
>https://issues.liferay.com/browse/LPS-92995
>
> https://issues.liferay.com/browse/LPS-90245 added support to search asset entry by class ids but caused regressions. For the default search we set subtypeSelectionId to null.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70557. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70558. [See changes here.](https://github.com/ealonso/liferay-portal/compare/cc627f44b391~2...cc627f44b391) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
