### PR TITLE
LPS-101762 Add test for copying categorization data

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79554. [See changes here.](https://github.com/ealonso/liferay-portal/compare/729966283ae6~2...729966283ae6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
