### PR TITLE
[TECHNICAL-SUPPORT] LPS-77365

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @ChrisKian

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
ci:stop

**Comment by jonathanmccann** [comment]
ci:stop

**Comment by jonathanmccann** [comment]
Tests passed here - https://github.com/jonathanmccann/liferay-portal/pull/1505

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/5642. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
