### PR TITLE
LPS-79348

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@ealonso, see https://github.com/hhuijser/liferay-portal/pull/3240 for some discussion regarding this fix

**Comment by arthurchan35** [comment]
@ealonso 
Regarding to the last comment from Hugo in https://github.com/hhuijser/liferay-portal/pull/3240, we had a discussion yesterday but didnt wrote it down.
Because that overloaded method was not directly called from jsp, if I had to add new parameters, I would have to create 4 extra overloaded methods for its calling methods, which is pretty ugly.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/158. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
