### PR TITLE
LPS-101568 Use Id or UUId instead of fragment key

### PR DESCRIPTION
**Pull request by csierra**
/cc @arthurchan35

### CODE REVIEW

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82274. [See changes here.](https://github.com/ealonso/liferay-portal/compare/ceba919ccfe2~2...ceba919ccfe2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82275. [See changes here.](https://github.com/ealonso/liferay-portal/compare/b8040f6327c7~3...b8040f6327c7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
