### PR TITLE
LPS-109979 Avoid left join against full table when there is no title involved in order by.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
@marianoalvarosaiz Could you please rebase and resend?

`Target exception: java.lang.RuntimeException: Unable to rebase marianoalvarosaiz-2818-LPS-109979 to master
error: Failed to merge in the changes.`

**Comment by marianoalvarosaiz** [comment]
see https://github.com/ealonso/liferay-portal/pull/2819

**Pull request closed without merging**
