### PR TITLE
[TECHNICAL-SUPPORT] LPS-87099

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
@jkappler Thank you! I'll forward future pull requests through you that would normally go to him if that works for you.

**Comment by jkappler** [comment]
great @jonathanmccann! In the meantime, I'll take a look at the other ones that you have already sent

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
sent here: https://github.com/brianchandotcom/liferay-portal/pull/64900

**Pull request closed without merging**
