### PR TITLE
LPS-79610 Pass language id parameter to be able to display the asset with appropriate locale

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/157. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
