### PR TITLE
LPS-113002 Adds new class to the control menu if the portlet is a global menu app

### PR DESCRIPTION
**Pull request by marcoscv-work**
Task to add the CSS required to use a new light control menu version:

To do this with the possibility to control variables, not by a CSS overwrite (possible future custom properties problems). I've created a style abstraction, for that we keep general box styles in the class: `control-menu-level-1` and I created:
`control-menu-level-1-dark` (added by default)
`control-menu-level-1-light`

How the abstraction works:

`control-menu-level-1-dark`:
image

`control-menu-level-1-light`
image

The task does not define hover states, so I've tried by adding the standard ones:
image

To use `control-menu-level-1-light` you will need to replace the class: `control-menu-level-1-dark`

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:stable

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
ci:stop

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/956. [See changes here.](https://github.com/ealonso/liferay-portal/compare/0adae5e90515~3...0adae5e90515) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:stop

**Pull request closed without merging**
