### PR TITLE
LPS-114729 Part 2 (Second try): Extend support in the generic tracker for service trackers that need to be able to return all available components for a given itemClassName

### PR DESCRIPTION
**Pull request by JorgeFerrer**
Thanks for the help @csierra

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:test:relevant

**Comment by JorgeFerrer** [comment]
ci:reopen

**Comment by JorgeFerrer** [comment]
ci:test:relevant

**Comment by JorgeFerrer** [comment]
ci:test:relevant

**Comment by JorgeFerrer** [comment]
ci:test:relevant

**Comment by JorgeFerrer** [comment]
@ealonso I think that both failures in test:relevant are unrelated to this pull. What do you think?

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/1066. [See changes here.](https://github.com/ealonso/liferay-portal/compare/72ff50b7a9d5~6...72ff50b7a9d5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
