### PR TITLE
LPS-107487 Moves header out of portlet.ftl and into its proper position in the layout

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by stsquared99** [comment]
@jbalsas @ealonso Just a heads up, I have a few more changes to add to our portion of the code, so please let me know when you are ready, I can send them to you or you can send this to me, either way. Thanks!

**Comment by jbalsas** [comment]
Hey @stsquared99, feel free to push commits on top of https://github.com/ealonso/liferay-portal/pull/2713/commits/a7d7650202294cc1c249bfcf25a7720c5be4de39 and send me another PR when ready.

We'll keep working on the side for the rest.

**Comment by jbalsas** [comment]
@ealonso, @stsquared99, we're getting close to having something we can push to `master`.

See https://github.com/eduardoallegrini/liferay-portal/pull/37 for more details.

@stsquared99, I think we can push it without the ChangeList addition and then once that's settled push the work done for it... what do you think?

**Comment by stsquared99** [comment]
@jbalsas That actually sounds great, thanks!

**Pull request closed without merging**
