### PR TITLE
J cords lps 99857

### PR DESCRIPTION
**Pull request by joshuacords**
Made change noted here: https://github.com/ealonso/liferay-portal/pull/2508/commits/523694be2847c0011269f30c5577b43e22936d1a

cc @jonathanmccann

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77385. [See changes here.](https://github.com/ealonso/liferay-portal/compare/c5fda703d873~1...c5fda703d873) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
