### PR TITLE
LPS-115915 Drafts should only be visible for their owners.

### PR DESCRIPTION
**Pull request by cgoncas**
Hey @ealonso!

I have used @pavel-savinov implementation to implement the search in Content Dashboard.

But I still have some doubts, when you have time to review this pull request, let me know so we can catch up about it.

Thanks!!

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @pavel-savinov and @ealonso , the broken test, is happening because the same behavior that we had for DRAFT, we still have it for SCHEDULED content :(.

Maybe we need to think a little bit more about the solution in the Web Content indexer :(.

**Comment by ealonso** [comment]
Closing it, since we discarted this.

**Pull request closed without merging**
