### PR TITLE
LPS-74297 Uses foundation component instead of journal

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53652. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53653. [See changes here.](https://github.com/ealonso/liferay-portal/compare/bc69406~1...bc69406) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
