### PR TITLE
Lps 104305

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-104305

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
PR sent here https://github.com/brianchandotcom/liferay-portal/pull/80862

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
