### PR TITLE
LPS-70648 regenerate service code

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/92. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/93. [See changes here.](https://github.com/ealonso/liferay-portal/compare/2a6bf19~1...2a6bf19) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
