### PR TITLE
[TECHNICAL-SUPPORT] LPS-73018

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hey @ealonso,

Sending this through you since it's dealing with layouts and whatnot, but I could be way off base so let me know if someone else would be better to do the review.

/cc @mbowerman

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:reopen

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/11. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
