### PR TITLE
LPS-71804 use appropriate kernel version

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by ealonso** [comment]
'Pull <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
'Pull <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
