### PR TITLE
LPS-28940 Make YouTube portlet a generic Video Embedder

### PR DESCRIPTION
**Pull request by arthurchan35**
@ealonso
I want to mention couple of key points for this pull request:

I think it's better to rename the module bundle name, bnd, and its java package names, but I am not sure how it would affect portal version and building system, so I am leaving it for now.
For cases like youtube and youtu.be, I had to make two sperate entries in system setting, because configuration framework does not like '|' bar in the regex, because it is using the '|' as delimiter.
Other points are listed in the commit comments.
Let me know if you have concerns about anything.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by arthurchan35** [comment]
ci:retest

**Comment by arthurchan35** [comment]
ci:retest

**Comment by arthurchan35** [comment]
ci:retest

**Comment by arthurchan35** [comment]
ci:retest

**Comment by arthurchan35** [comment]
ci:retest

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Hi @arthurchan35, something seems to have happened with the PR. Could you send it to me please? Also, on your comment: Maybe it would be better to change the portlet`s name instead of maintaining youtube portlet (or even create a new one)? What do you think about this?

Thanks

**Pull request merged**
