### PR TITLE
Use searchContainer to track element selection

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37539. [See changes here.](https://github.com/ealonso/liferay-portal/compare/91b5eb9~18...91b5eb9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Daldi, al final no has pasado nada del searchcontainer?

**Comment by ealonso** [comment]
Tu no estas en un avion???

**Comment by ealonso** [comment]
como me espias, que fuerte, lo tengo en otra rama para mandarlo en otra pull, que Jorge decia que aqui mejor hacer seleccion multiple, cuando lo pase te menciono, tranquilo

**Comment by jbalsas** [comment]
en coche, en avión o en cohete... yo siempre estoy vigilando... :wink:

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37756. [See changes here.](https://github.com/ealonso/liferay-portal/compare/193e6aa~11...193e6aa) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37757. [See changes here.](https://github.com/ealonso/liferay-portal/compare/16900ac~10...16900ac) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37758. [See changes here.](https://github.com/ealonso/liferay-portal/compare/e21fa65~11...e21fa65) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
