### PR TITLE
[TS] LPS-103591

### PR DESCRIPTION
**Pull request by ChrisKian**
From @jesseyeh-liferay:

> ## Problem :grimacing:
> 
> **[LPS-103591](https://issues.liferay.com/browse/LPS-103591)**
> 
> When clicking on the "Find a Page" button, a Site with at least three nested pages will show a tree structure with an invisible (but interactable) expand/collapse icon next to the second nested page.
> 
> ## Analysis :nerd_face: 
> 
> #### Frontend
> Examining the tree structure reveals that the `value` being passed into `_parseLayouts()` in `layouts_tree.js` is erroneous to begin with. For example, a tree structure consisting of four nested pages will be incorrectly processed as a tree structure that only goes two pages deep -- the `childrenLength` for the second page is incorrectly shown to be zero. Thus, we look into the implementation for how the tree is constructed in `LayoutsTreeImpl.java`.
> 
> #### Backend
> Within `LayoutsTreeImpl.java`, `_getLayoutTreeNodes()` is a recursive function containing a call to `_isExpandableLayout()` that checks the current `Layout`'s `ancestorLayouts` to determine if it is expandable. We focus on a segment in the original implementation for `_getLayoutTreeNodes()`, which is outlined in pseudocode below:
> 
> 1. Call `_getLayoutTreeNodes()`
> 2. Get the `ancestorLayouts` of the passed-in `Layout`
> 3. For each child `Layout` of the passed-in `Layout`, if it is contained in `ancestorLayouts`, then it is considered expandable
> 4. Recurse (Step 1) on the passed-in `Layout`
> 
> The error lies in Step 2 above. When we recurse, we end up using the parent's `Layout` instead of the child's. While we can swap the logic so that Step 2 occurs after Step 3 to resolve the issue, further examination of `_getAncestorLayouts()`'s and `_isExpandableLayout()`'s original implementations yields another step we can take.
> 
> #### An Additional Step
> In the original implementation, [`_getAncestorLayouts()` considers the current layout to be its own ancestor](https://github.com/jesseyeh-liferay/liferay-portal/blob/882587859438ef3a55bcc673f660588fca50399c/modules/apps/layout/layout-impl/src/main/java/com/liferay/layout/internal/util/LayoutsTreeImpl.java#L311) and [`_isExpandableLayout()` checks for the same](https://github.com/jesseyeh-liferay/liferay-portal/blob/882587859438ef3a55bcc673f660588fca50399c/modules/apps/layout/layout-impl/src/main/java/com/liferay/layout/internal/util/LayoutsTreeImpl.java#L540). With this in mind, swapping Step 2 and Step 3, so that the correct `Layout` is its own ancestor, would be redundant, as [the `isExpandableLayout()` conditional would always return `true`](https://github.com/jesseyeh-liferay/liferay-portal/blob/882587859438ef3a55bcc673f660588fca50399c/modules/apps/layout/layout-impl/src/main/java/com/liferay/layout/internal/util/LayoutsTreeImpl.java#L358).
> 
> ## Solution :tada:
> 
> To recap, the original error is caused by an incorrect order in logic; swapping Step 2 so that it takes place after Step 3 above displays the hitarea icons correctly. However, we can take a further step by removing the `_isExpandableLayout()` conditional, which solves the original problem and also eliminates redundancy.
> 
> This solution also removes the `_fetchCurrentLayout()`, `_getAncestorLayouts()`, and `_isExpandableLayout()` methods to comply with the source formatter.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80147. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
