### PR TITLE
LPS-112372 Add micro-framework to Info Framework to allow describing the fields of a given entity

### PR DESCRIPTION
**Pull request by JorgeFerrer**
This is Step 1. Next I'll send implementations of the enw frameworks

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
In case you find it useful to check what's coming next, I've grouped it all in one commit to facilitate looking it up here: JorgeFerrer@98182e8

**Comment by JorgeFerrer** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/747. [See changes here.](https://github.com/ealonso/liferay-portal/compare/723eeea0fba6~6...723eeea0fba6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Thanks Carlos. I've fixed them and I will send them in the next pull which will probably have more changes to the tracker.

**Comment by JorgeFerrer** [comment]
Thanks for the review and the changes @ealonso

**Pull request closed without merging**
