### PR TITLE
LPS-102202

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/79418

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79442. [See changes here.](https://github.com/ealonso/liferay-portal/compare/d0866b760045~2...d0866b760045) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/victorg1991/liferay-portal/pull/108. [See changes here.](https://github.com/ealonso/liferay-portal/compare/36e3fce0a877~23...36e3fce0a877) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
