### PR TITLE
[TECHNICAL-SUPPORT] LPS-78392

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @JonathanAichler

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @SamZiemer,

I'm working in this issue but this is taking more time than I expected, the problem with your fix is we are changing the url to something like this: http://localhost:8080/web/guest/home/-/categories/37102?p_r_p_resetCur=true, ideally it should not be change, so we should have an url like this: http://localhost:8080/web/guest/home/-/categories/37102.

I'm trying to find a solution but I need more time.

Regards,
Eudaldo.

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/118. [See changes here.](https://github.com/ealonso/liferay-portal/compare/487f06ab6a4b~2...487f06ab6a4b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
