### PR TITLE
LPS-103353 The delimiter for keyword filters definitions should be space but is comma

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test:sf

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
sent here: https://github.com/brianchandotcom/liferay-portal/pull/79753

thanks @rotty3000, this fixes another issue that we got

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
