### PR TITLE
LPS-115840 Split FormProvider, moving methods to retrieve values to a new InfoItemValuesProvider service (Rebased)

### PR DESCRIPTION
**Pull request by JorgeFerrer**
@4lejandrito @adolfopa

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/1230. [See changes here.](https://github.com/ealonso/liferay-portal/compare/6704755cebb1~2...6704755cebb1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/1238. [See changes here.](https://github.com/ealonso/liferay-portal/compare/3def0303a093~2...3def0303a093) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
