### PR TITLE
LPS-114729 Replace the trackers for InfoItemFormProvider and InfoItemObjectProvider with a new generic tracker

### PR DESCRIPTION
**Pull request by JorgeFerrer**
Thanks @csierra for the suggestion

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:test:relevant

**Comment by JorgeFerrer** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/972. [See changes here.](https://github.com/ealonso/liferay-portal/compare/6599636ca87b~1...6599636ca87b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
