### PR TITLE
LPS-100792

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-100792

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/584. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
