### PR TITLE
LPS-77484 UpgradeJournalArticleImage: covering the 6.1.x upgrade case

### PR DESCRIPTION
**Pull request by achaparro**
cc/ @inacionery @marcellustavares

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test

**Comment by achaparro** [comment]
Error caused by
ModulesStructureTest.testScanBuildScripts fails due to commit 7a2e9cb

**Comment by achaparro** [comment]
ci:reopen

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54828. [See changes here.](https://github.com/ealonso/liferay-portal/compare/93ca840~1...93ca840) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
