### PR TITLE
LPS-105137 Duplicate the existing item and add it next to the duplicated

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/julien/liferay-portal/pull/190. [See changes here.](https://github.com/ealonso/liferay-portal/compare/25393124ca98~5...25393124ca98) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
