### PR TITLE
LPS-104108 | Asset Publisher could display assets for all personalized views that a user belongs to

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi @ealonso, 

This issue was reported by a customer in 7.2. [PTR-1478](https://issues.liferay.com/browse/PTR-1478) determined that we should fix it since it can be regarded a feature loss from 7.1 to 7.2. 

The idea is that a user belonging to several segments could be shown all the assets for all personalized views associated to each segment in a given content set, manual or dynamical. This is controlled by a system settings, set to false by default.

Manual and dynamic cases must be treated separately. 

- For the manual case we can add a new finder that retrieves in a single queries all assets under a list of personalized views. 
- For the dynamic case we have to do a query for each segmentId and combine the results respecting pagination. (See [PTR-1478](https://issues.liferay.com/browse/PTR-1478) for context on why we don't try to do a single query.) 

Note that even if pagination is active, the asset publisher will retrieve all assets and then take a sublist of them, so we only worry about pagination in the modified code because of the signature of the methods including start and end. 

Please let me know if you have any question. Thanks!

### CODE REVIEW

**Comment by ricardocousolr** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
Hey @ricardocousolr,

Pavel is working on the review.

cc: @pavel-savinov

**Comment by ricardocousolr** [comment]
Thanks, @ealonso !

**Pull request closed without merging**
