### PR TITLE
LPS-XXXXX Applies liferay-frontend:component to trash-web

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67642. [See changes here.](https://github.com/ealonso/liferay-portal/compare/87a1f92e921c~4...87a1f92e921c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67672. [See changes here.](https://github.com/ealonso/liferay-portal/compare/7422ab1ad933~24...7422ab1ad933) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
