### PR TITLE
LPS-78279 Buildlang

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55983. [See changes here.](https://github.com/ealonso/liferay-portal/compare/027eb7e0fca0~13...027eb7e0fca0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56021. [See changes here.](https://github.com/ealonso/liferay-portal/compare/dbda93186ec8~14...dbda93186ec8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
