### PR TITLE
LPS-81721 SF

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
cc @jbalsas

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59424. [See changes here.](https://github.com/ealonso/liferay-portal/compare/7ca956763516~1...7ca956763516) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59447. [See changes here.](https://github.com/ealonso/liferay-portal/compare/91ca0b516458~8...91ca0b516458) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
