### PR TITLE
LPS-107294 This param is never set, so it's always false and the preference is not stored

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83516. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
