### PR TITLE
Lps 107104 katie

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @katienesterovich

Notes from Katie
> Caused by removal of soy templates in [LPS-100134](https://issues.liferay.com/browse/LPS-100134) [5848c49](https://github.com/brianikim/liferay-portal/commit/5848c49ce3585f29f97482ad6b24630f3778e43e) and moving implementation to React in [LPS-100140](https://issues.liferay.com/browse/LPS-100140) [72cf6b4](https://github.com/brianikim/liferay-portal/commit/72cf6b4a0d0c16f101fb7f077465a5f53923a954).

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by katienesterovich** [comment]
ci:reopen

**Comment by katienesterovich** [comment]
Hey @ealonso,
I don't think the .gitrepo issue is related to my commits so I re-opened the PR. (Please let me know if I'm mistaken).
Thanks!

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84067. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
