### PR TITLE
LPS-78985 Adds default navigation menu if we don't have navigation menus when we visit the layouts admin portlet

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by ealonso** [comment]
ci:test

**Comment by ealonso** [comment]
Hey @anthony-chu,

Do you know why those test are failing?

Regards,
Eudaldo.

**Comment by anthony-chu** [comment]
hi @ealonso, it looks like in the navigation menu, all of the pages are marked `active` and so navigation is not successful. we assume that any page that is not the current page does not have `active` as one of the css classes and check that `active` is added as a css class if that page is the current page.

**Comment by ealonso** [comment]
@anthony-chu, thanks you very much!!!, you saved me a lot of time, 👏 👏 👏

**Pull request closed without merging**
