### PR TITLE
LPS-79988 Use correct URL when there's no display page for the article

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59575. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by laszlopap** [comment]
Hi @jkappler ,

Thank you for helping with this issue. 

Hi @ealonso,

I would like to ask for some information, which helps me to better understand this issue and the future issues related to this part of the portal:

Here: https://github.com/dacousalr/liferay-portal/pull/35/files  
We have tried to fix the url prefix causing the issue. Also there is a request to create a DB script which fixes URLs already stored in the DB. 

As far as I can see, this PR is based on the SME request for URL generation, which is a very important part here.

However this PR does not contain a fix for the LPS, which is about url prefix. Am I wrong here? Please help me with this, because I want to find the best solution.

Thanks,
László

**Comment by jkappler** [comment]
Hey @laszlopap, as was mentioned in the LPS in jira, we were generating the URL wrong. This was caused by LPS-76339, since there it was introduced that when a display page for a WC exists, that link should be used. 

The only change was defaulting to the full URL of control panel in case the URL for the display page doesn't exists (serviceContext.getCurrentURL() doesn't containt the host). This was done before LPS-76339, but somehow got lost in the process.

**Pull request closed without merging**
