### PR TITLE
LPS-73070 Creates package-lock files (auto-generated)

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/1102. [See changes here.](https://github.com/ealonso/liferay-portal/compare/0d086e02c3ac~4...0d086e02c3ac) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
👀

**Comment by ealonso** [comment]
pero esto que es?

**Comment by jbalsas** [comment]
:shrug:

Ecos del pasado?

**Comment by ealonso** [comment]
es el tonto GH, que se confunde

**Comment by jbalsas** [comment]
me he quedao to loco

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/1109. [See changes here.](https://github.com/ealonso/liferay-portal/compare/651ab76f3670~4...651ab76f3670) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/1114. [See changes here.](https://github.com/ealonso/liferay-portal/compare/651ab76f3670~4...651ab76f3670) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
A estas horas, @ealonso? 😴

**Comment by ealonso** [comment]
😂

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/90233. [See changes here.](https://github.com/ealonso/liferay-portal/compare/651ab76f3670~4...651ab76f3670) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
esto ya empieza a ser un poco abusivo, eh?

**Comment by ealonso** [comment]
A tope, ya no pasa más

**Pull request closed without merging**
