### PR TITLE
LPS-77816 Missing language key

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55450. [See changes here.](https://github.com/ealonso/liferay-portal/compare/bcb6aabcba14~13...bcb6aabcba14) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55454. [See changes here.](https://github.com/ealonso/liferay-portal/compare/49d9653f1ff4~19...49d9653f1ff4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
