### PR TITLE
LPS-112925 Copy default experience embedded portlet preferences when creating a new experience

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/564. [See changes here.](https://github.com/ealonso/liferay-portal/compare/4a7ca627ceea~1...4a7ca627ceea) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/565. [See changes here.](https://github.com/ealonso/liferay-portal/compare/696cb8a73683~1...696cb8a73683) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
