### PR TITLE
LPS-107564 Add unit tests for AnalyticsReportsDisplayContext

### PR DESCRIPTION
**Pull request by dgarciasarai**
/cc @darquesdev

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83958. [See changes here.](https://github.com/ealonso/liferay-portal/compare/6d81a9fab5fd~2...6d81a9fab5fd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/darquesdev/liferay-portal/pull/111. [See changes here.](https://github.com/ealonso/liferay-portal/compare/6d81a9fab5fd~2...6d81a9fab5fd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
