### PR TITLE
LPS-44217 semver

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by rotty3000** [comment]
@ealonso do you have any comments on this? Perhaps I can have someone work on the UI improvements needed?

**Comment by ealonso** [comment]
Hey @rotty3000,

I was ooo last week and I would like to wait for @jorgeFerrer to discuss the solution.

Regards,
Eudaldo.

**Comment by rotty3000** [comment]
No problem! I am at your disposal to discuss any questions.

**Pull request closed without merging**
