### PR TITLE
LPS-76859 Adds dropdown-item to links within icon menus

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dacousalr** [comment]
Hi @jbalsas,

As discussed with @ealonso, this PR was closed since Master is going to have a different solution but in any case this fix can be a valid backport for 7.0.

Please, let me know if I am wrong.

Thanks,
Daniel

**Comment by fortunatomaldonado** [comment]
Hello @jbalsas @ealonso ,

Will the fix I created be usable for a 7.0.x specific fix, or will we be waiting for Master's implementation and backport that to 7.0.x?
Thanks for the help.

**Comment by ealonso** [comment]
Hey @fortunatomaldonado,

As @dacousalr commented, you can use it for 7.0.x.

Regards,
Eudaldo

**Comment by MichaelPrigge** [comment]
Hello @dacousalr and @ealonso,

I was wondering if you could explain to us how the master solution is going to be different? Is this different master solution that you suggested earlier on this pull going to be in some way incompatible with 7.0.x or could it also apply to 7.0.x?

Further more I was wondering if you had any sort of update or timeline for when the master solution is going to be worked on/resolved?

I appreciate any feedback you can give on these matters.

Thanks!

**Pull request closed without merging**
