### PR TITLE
LPS-72641 SF

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by p2kmgcl** [comment]
[#1006](https://github.com/ealonso/liferay-portal/pull/1006)

**Comment by p2kmgcl** [comment]
@ealonso please close this pr and check 1006

**Comment by jbalsas** [comment]
Hey @p2kmgcl, I've closed it, but you should update https://issues.liferay.com/browse/LPS-72641 with the new information 😉 

Let me know if you have any questions about the workflow!

**Comment by p2kmgcl** [comment]
@jbalsas I was told, but I am still getting used to :)
Im going to update it right now

**Comment by jbalsas** [comment]
😉

**Pull request closed without merging**
