### PR TITLE
LPS-145798 Apply DROP_TABLE_IF_EXISTS to avoid bad termination of UpgradeReportLogAppenderTest on DB2

### PR DESCRIPTION
**Pull request by LuisOrtiz89**
LPS-145798

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by LuisOrtiz89** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by LuisOrtiz89** [comment]
ci:reevaluate:1307401_2719

**Comment by LuisOrtiz89** [comment]
ci:forward

**Comment by LuisOrtiz89** [comment]
ci:forward

**Comment by LuisOrtiz89** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by LuisOrtiz89** [comment]
ci:test:relevant

**Comment by LuisOrtiz89** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by LuisOrtiz89** [comment]
ci:forward

**Comment by LuisOrtiz89** [comment]
ci:forward

**Comment by LuisOrtiz89** [comment]
ci:forward

**Comment by LuisOrtiz89** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-upgrades/liferay-portal/pull/311. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
