### PR TITLE
LPS-163094

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@ealonso see https://github.com/brianchandotcom/liferay-portal/pull/123315

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/9675. [See changes here.](https://github.com/ealonso/liferay-portal/compare/f17d6efc5816~4...f17d6efc5816) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/9676. [See changes here.](https://github.com/ealonso/liferay-portal/compare/f17d6efc5816~4...f17d6efc5816) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/9676

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/123410. [See changes here.](https://github.com/ealonso/liferay-portal/compare/d6e932cd5135~4...d6e932cd5135) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
