### PR TITLE
LPS-75533 Render the AssetEntry also if the user has permission to view.

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54538. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
