### PR TITLE
LPS-107617 Use AnalyticsReportsInfoItems to inject properties to Display Context

### PR DESCRIPTION
**Pull request by darquesdev**
@dgarciasarai

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83866. [See changes here.](https://github.com/ealonso/liferay-portal/compare/0873708a0b2e~5...0873708a0b2e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
