### PR TITLE
LPS-101769 Replace 'fragmentEntryLinkUuid' with 'fragmentEntryLinkNamespace' since it does not change when a page is published

### PR DESCRIPTION
**Pull request by darquesdev**
@pavel-savinov @manoelcyreno

### CODE REVIEW

**Comment by manoelcyreno** [comment]
ci:test:bundle

**Comment by manoelcyreno** [comment]
ci:test:sf

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78639. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
