### PR TITLE
LPS-64308 Implement toggleDisableInputs

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
- Squash "LPS-64308 Squash this with previous colorpicker creation" with "	LPS-64308 Create ColorPickerInput metal component"

- Squash "LPS-64308 Add disabled property to ColorPickerInput" with "LPS-64308 Create ColorPickerInput metal component"

**Comment by carloslancha** [comment]
cc @jbalsas

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/703. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
cc @ealonso

**Pull request closed without merging**
