### PR TITLE
LPS-73558 Change the UI for creating/editing categories in asset categories admin

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:retest

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50296. [See changes here.](https://github.com/ealonso/liferay-portal/compare/4b3ad15~11...4b3ad15) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
