### PR TITLE
LPS-106824 Provide endpoint to retrieve views

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/dgarciasarai/liferay-portal/pull/158. [See changes here.](https://github.com/ealonso/liferay-portal/compare/9595ec809b82~1...9595ec809b82) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
