### PR TITLE
[TS] LPS-88435 XSS in Directory Indexing

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-88435

Author: @istvansajtos
Reviewers: @lipusz
App Security review: :heavy_check_mark: 

Thanks Eudaldo!

Regards,
Tibor

>When browsing documents via the Directory Indexing feature, the HTML is generated from a FreeMarker template (used by WebServerServlet). In this template we display the description of DLFolders and DLFileEntries without escaping.

> FYI, only description needs escaping, because name has restrictions for special characters out-of-the-box

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65975. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
