### PR TITLE
LPS-110227 Category Navigation portlet is not shown for different experience segment

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/474. [See changes here.](https://github.com/ealonso/liferay-portal/compare/30ce9ac68eb5~4...30ce9ac68eb5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
