### PR TITLE
LPS-88400 Create a hidden Layout for each asset display page entry and associate new Layout with the entry.

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65880. [See changes here.](https://github.com/ealonso/liferay-portal/compare/3a7d94ad35f9~2...3a7d94ad35f9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
