### PR TITLE
LPS-78768 Disable pretty print to avoid introducing extra spaces

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by pavel-savinov** [comment]
cc @jkappler

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56129. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
