### PR TITLE
[TS] LPS-79348

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevent

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60339. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60341. [See changes here.](https://github.com/ealonso/liferay-portal/compare/0c71e8d10635~1...0c71e8d10635) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
