### PR TITLE
LPS-114565

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @ealonso, I have been working on adding generics for types that use generics.
I ran into issues with `journal` and rewrote things a bit in this pull.
Can you have a look?

Thanks!

**Comment by hhuijser** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:stop

**Comment by hhuijser** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/875. [See changes here.](https://github.com/ealonso/liferay-portal/compare/8eca4400194a~5...8eca4400194a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
