### PR TITLE
[TS] LPS-99786

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-99786

CC @balazssk

Discussed in [PTR-1113](https://issues.liferay.com/browse/PTR-1113), the correct solution is to allow the page template to be created initially, even if there is a requirement for a category to be present.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77137. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
