### PR TITLE
LPS-78178 We don't need edit stuff because layout type controller is not instantiable

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by pavel-savinov** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55788. [See changes here.](https://github.com/ealonso/liferay-portal/compare/8d8f353c093d~2...8d8f353c093d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
