### PR TITLE
LPS-95926 Adapt journal article template

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
ci:test:relevant <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73769. [See changes here.](https://github.com/ealonso/liferay-portal/compare/cd94cdfcb7e5~2...cd94cdfcb7e5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
