### PR TITLE
LPS-91548

### PR DESCRIPTION
**Pull request by samuelkong**

### CODE REVIEW

**Comment by samuelkong** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
@adolfopa

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/885. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
