### PR TITLE
LPS-98325 Use correct language key for converting to content page

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/ruben-pulido/liferay-portal/pull/141. [See changes here.](https://github.com/ealonso/liferay-portal/compare/82cbd5cad0db~5...82cbd5cad0db) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
