### PR TITLE
LPS-93306 Declare the dependency with the configuration and annotate the activate method as modified

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70774. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
