### PR TITLE
LPS-84039

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
@hhuijser, @ealonso is ooo, PR sent here: sent here: https://github.com/brianchandotcom/liferay-portal/pull/62049

**Comment by jkappler** [comment]
ci:close

**Comment by hhuijser** [comment]
Thanks @jkappler !

Would you mind also having a look at these 3 classes?

com.liferay.asset.publisher.web.display.context.AssetEntryResult
com.liferay.asset.publisher.web.util.AssetPublisherHelper
com.liferay.asset.publisher.web.util.AssetPublisherUtil

Those are all deprecated, but are still being called by others.

**Comment by jkappler** [comment]
sure @hhuijser, will try to take a look at them today. Thanks for letting me know

**Pull request closed without merging**
