### PR TITLE
LPS-96702 Add render-fragment-layout taglib

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/victorg1991/liferay-portal/pull/29. [See changes here.](https://github.com/ealonso/liferay-portal/compare/b9656f63e33d~5...b9656f63e33d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
