### PR TITLE
LPS-69482 Simplify url generation by removing p_p_col_id,  p_p_col_pos and  p_p_col_count parameters

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @jbalsas

**Comment by sergiogonzalez** [comment]
cc/ @juliocamarero

**Comment by jbalsas** [comment]
Hey @sergiogonzalez, isn't this at least a breaking change worth documenting?

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/45180. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
