### PR TITLE
[TECHNICAL-SUPPORT] LPS-77038

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @ChrisKian

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
ci:stop

**Comment by jonathanmccann** [comment]
Tests passed here - https://github.com/jonathanmccann/liferay-portal/pull/1506

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54689. [See changes here.](https://github.com/ealonso/liferay-portal/compare/946ac98~3...946ac98) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
