### PR TITLE
[TS] LPS-94767

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-94767

CC @jrao

We decided to change the message since there are cases where the portlet never existed rather than is just undeployed.  This new message is more general.

Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72386. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
