### PR TITLE
LPS-93201 Regen

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
@ealonso @jorgeferrer the first changes for experience-based custom page structures. Notice that I had to use a reduced version of the Rel table, as the complete name would exceed the limits.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70685. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
