### PR TITLE
[TECHNICAL-SUPPORT] LPS-89632

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-89632

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:test

**Comment by JosemariaMunoz** [comment]
ci:retest

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67356. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JosemariaMunoz** [comment]
Thanks a lot @ealonso! 👍

**Pull request closed without merging**
