### PR TITLE
LPS-79748 permissive filterGroups based on permissions instead of roles

### PR DESCRIPTION
**Pull request by SpencerWoo**
Resent from 
https://github.com/ealonso/liferay-portal/pull/1601

/cc @jonathanmccann

Made the same/equivalent changes on a new commit and newer master.

### CODE REVIEW

**Comment by SpencerWoo** [comment]
ci:test

**Comment by SpencerWoo** [comment]
Hi @ealonso any updates with this one?

**Comment by ealonso** [comment]
Hey @SpencerWoo,

@dacousalr is taking a look at it, because with your change is possible to broke many use cases, because this browser is used in other places not only in your case and also could be use for clients in their custom developments.

Regards,
Eudaldo.

**Comment by SpencerWoo** [comment]
sounds good, thanks for the update!

**Comment by SpencerWoo** [comment]
Hi @dacousalr any updates for this?

**Comment by dacousalr** [comment]
Hi @SpencerWoo,

I have done a static analysis and it seems weird to me to check the Assign Members permission in the user personal site as a equivalent method to check if the user is the company Administrator. It would be more reasonable to check it against the company group (Global), although this change and previous one should review more in depth.

I would also like to do a dynamic analysis to complete my review but it does not compile. Could you add the commits to make it compilable?

Thanks in advance

**Comment by ealonso** [comment]
@SpencerWoo 

Please add the needed commits to compile and resend to @dacousalr 

Thanks!!,
Eudaldo.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/1629. [See changes here.](https://github.com/ealonso/liferay-portal/compare/221f3c9c9ae9~1...221f3c9c9ae9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
