### PR TITLE
LPS-79708 Move "Display Pages" to a tab along with "Pages" and "Page Templates"

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57313. [See changes here.](https://github.com/ealonso/liferay-portal/compare/10c3bce2ec6b~4...10c3bce2ec6b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57336. [See changes here.](https://github.com/ealonso/liferay-portal/compare/b935f6baba70~5...b935f6baba70) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
