### PR TITLE
LPS-110677 No needed

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by jpince** [comment]
@xbrianlee see DM failures in the second run - potential flakiness?
```
LIFERAY_ERROR: java.lang.RuntimeException: org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: ProcessClusterEventTimeoutException[failed to process cluster event (create-index [liferay-search-tuning-synonyms-liferay-40481], cause [api]) within 30s]
LIFERAY_ERROR: javax.portlet.PortletException: java.lang.RuntimeException: org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: ProcessClusterEventTimeoutException[failed to process cluster event (create-index [liferay-search-tuning-synonyms-liferay-40481], cause [api]) within 30s]
```

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Pull request closed without merging**
