### PR TITLE
LPS-106349 Avoid creating the config everytime the store changes

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/victorg1991/liferay-portal/pull/134. [See changes here.](https://github.com/ealonso/liferay-portal/compare/95fe235340a0~14...95fe235340a0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
