### PR TITLE
LPS-79631 SF

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57200. [See changes here.](https://github.com/ealonso/liferay-portal/compare/4e8b40b8a634~1...4e8b40b8a634) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57224. [See changes here.](https://github.com/ealonso/liferay-portal/compare/0521159dcd03~2...0521159dcd03) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
