### PR TITLE
LPS-68868 missing dependencies

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/47950. [See changes here.](https://github.com/ealonso/liferay-portal/compare/fbb96ec~4...fbb96ec) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
