### PR TITLE
LPS-76346 Use default instance or site workflow configuration if it is not defined for the current folder

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by pavel-savinov** [comment]
ci:test

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55066. [See changes here.](https://github.com/ealonso/liferay-portal/compare/10df3e8~2...10df3e8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55068. [See changes here.](https://github.com/ealonso/liferay-portal/compare/2e4409e~2...2e4409e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
