### PR TITLE
LPS-194756

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
@victorg1991 fallan un poquito los tests, 😂

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Comment by alessandromalves** [comment]
Only two unique failures were found by the CI ([comparison with acceptance routine here](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1693406890962&testrayRunIdA=2414574057&testrayRunIdB=2415557276)) and were not reproducible locally. The others are not related to this PR.

**Pull request closed without merging**
