### PR TITLE
LPS-78272 Adjust timeline and buttons styles

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by beatrizma** [comment]
It's ok for me Pavel
image

**Comment by pavel-savinov** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55787. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
