### PR TITLE
LPS-101946 Return the sort function to journal history

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @joshuacords

Notes from Josh:

> https://issues.liferay.com/browse/LPS-101946
> https://issues.liferay.com/browse/LPP-35112
> 
> This issue was caused by LPS-78342 where they did not add `articleSearchContainer.setOrderByType()` in their creation of [JournalHistoryDisplayContext](https://github.com/brianchandotcom/liferay-portal/pull/57364/files#diff-9909f289205f0a11bf1e969b39169a1cR121) whereas it was correctly added to a similar file: [JournalViewMoreMenuItemsDisplayContext](https://github.com/brianchandotcom/liferay-portal/pull/57364/files#diff-f1548a53ec491eddf667e0e80b6c4c28R96).
> 
> Adding the orderers resolves the issue.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78735. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
