### PR TITLE
[TECHNICAL-SUPPORT] LPS-97649

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @knchau

Notes from Kim: 

> https://issues.liferay.com/browse/LPS-97649
> 
> [LPS-93425](https://issues.liferay.com/browse/LPS-93425) commits https://github.com/brianchandotcom/liferay-portal/pull/71240/commits/76552bc9b366001f4e4db45488ffb2d52f8db271 that does not allow a character to be a friendly URL because there are friendly URL that contain specific characters ([comment](https://issues.liferay.com/browse/LPS-93425?focusedCommentId=1755856&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1755856) from LPS-93425).
> 
> I changed the pattern to only contain the characters I found in the project. 
> 
> /b for blogs
> /d for documents
> /w for web-content

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Please see: https://issues.liferay.com/browse/LPS-97649

**Pull request closed without merging**
