### PR TITLE
LPS-85472

### PR DESCRIPTION
**Pull request by jonathanmccann**
@ealonso,

I wasn't sure about https://github.com/ealonso/liferay-portal/compare/master...jonathanmccann:LPS-85472?expand=1#diff-bca2f6bb6ea8efb46878d26b70105e96R201 since I do not know if the template set in the configuration of the Web Content Display widget will ever be different from the template set on the article itself.

If they will never be different, we can remove this block and make the same change here https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-content-web/src/main/java/com/liferay/journal/content/web/internal/portlet/JournalContentPortlet.java#L113-L114

If there is a reason we need to pass in `null` and `1` for the parameters here, please let me know and I will investigate a different solution.

Thanks.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63164. [See changes here.](https://github.com/ealonso/liferay-portal/compare/2a05e6cfa6f8~1...2a05e6cfa6f8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
