### PR TITLE
LPS-97990 Replace experience ids in FreemarkerProcessor section of editableValues when importing content references

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
ci:test:relevant <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75882. [See changes here.](https://github.com/ealonso/liferay-portal/compare/8fe55ef44c92~4...8fe55ef44c92) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
