### PR TITLE
LPS-97731 Verify configuration and editable values when updating fragment entry links with propagation

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
ci:test:relevant <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/ruben-pulido/liferay-portal/pull/101. [See changes here.](https://github.com/ealonso/liferay-portal/compare/c400b0108607~2...c400b0108607) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
