### PR TITLE
LPS-73546 The scope is not matching

### PR DESCRIPTION
**Pull request by jkappler**
cc:// @p2kmgcl

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:retest

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50277. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
