### PR TITLE
LPS-96688 Include fragment configuration when importing fragments

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
ci:test:relevant <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75104. [See changes here.](https://github.com/ealonso/liferay-portal/compare/209bdc247ad1~1...209bdc247ad1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
