### PR TITLE
LPS-107685 If backgroundImage is not present return null. Fixes failing test LayoutDataConverterTest.testConvertComplete (https://github.com/brianchandotcom/liferay-portal/pull/83850#issuecomment-579356542)

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
