### PR TITLE
LPS-94554 Verify that the classPK property in the json is null, do not rely on Getter.getLong which returns a 0 when the json is empty `{}`

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72067. [See changes here.](https://github.com/ealonso/liferay-portal/compare/88895f0824be~1...88895f0824be) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
