### PR TITLE
LPS-90864 Let users see groups they belong to

### PR DESCRIPTION
**Pull request by adolfopa**
The previous fix (adding a special case when filtering) is not enough.
Unless we extend the permission check, creating shortcuts between sites
fails.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72226. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
