### PR TITLE
LPS-113704 Improve performance of LayoutPageTemplateServiceUpgrade process 3.2.0 to 3.3.0

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/675. [See changes here.](https://github.com/ealonso/liferay-portal/compare/19683ce8d3b5~1...19683ce8d3b5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
