### PR TITLE
LPS-115658 We could use the javax.portlet.init-param.config-template param.

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/1274. [See changes here.](https://github.com/ealonso/liferay-portal/compare/75caaaa2e31b~3...75caaaa2e31b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
