### PR TITLE
LPS-90058 Adjust new Asset Publisher paths

### PR DESCRIPTION
**Pull request by kyle-miho**

### CODE REVIEW

**Comment by kyle-miho** [comment]
@ealonso there are a lot of conflicts with the base master branch (see below for reference). Could you take a look at it? Thanks!
https://github.com/kyle-miho/liferay-portal/pull/151

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68661. [See changes here.](https://github.com/ealonso/liferay-portal/compare/4f2474777713~1...4f2474777713) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68750. [See changes here.](https://github.com/ealonso/liferay-portal/compare/869dcd36e748~2...869dcd36e748) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
