### PR TITLE
[TECHNICAL-SUPPORT] LPS-53432 (fix + test) Asset Publisher sorts entries incorrectly by Title on non-default locales

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-53432

Hey Eudaldo,

Hope you're doing well.
Please, see the LPS for description and screenshots.

I'd like to ask you to also read my additional comments on the ticket, to get a detailed context about the issue and a possible alternative solution that could be used only by/in Elasticsearch. I decided not to follow that approach, since users shall switch from ES to Solr in 7.0 as well, and the behavior should remain consistent across different engines.

I'm also sending you a fix-only pull in case you'd like to rethink the integration test, so you can proceed and push forward the fix if you agree with my solution.

Best,
-tibor

### CODE REVIEW

**Comment by lipusz** [comment]
Notes for the test: I had problems running integration tests on today master: something with spring initialization is broken, so the tests don't run.

To test my test (:-), I applied the commits on 62x (https://github.com/lipusz/liferay-portal-ee/tree/LPS-53432-ee-6.2.x) where the BlogsEntrySearchTest#testLocalizedSortByTitle ran successfully and passed.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hi @lipusz,

We have a test class for asset, it is BaseAssetSearchTestCase and we have a  method that check the order by title see testOrderByTitleDesc. Could you check if this method covers your case? If not, could you add a new test on BaseAssetSearchTestCase for that.

Thanks your very much!!!,
Eudaldo.

**Comment by lipusz** [comment]
Hey Eudaldo,

Thanks for the quick response. I'll check BaseAssetSearchTestCase.
Apart from the test, is there anything else you want from me to adjust, or the fix itself is fine?

Thank you!

@ealonso

**Comment by lipusz** [comment]
Hey Eudaldo,

I think, BaseAssetSearchTestCase is not a good place to test this, since it deals with tags and categories only.
We need to test is with entries that cannot we have localized titles. Do you still think I should move the code there?

@ealonso

**Comment by ealonso** [comment]
Hey Tibor,

I think the test should be work in both cases, when we can translate the title and when we cannot translate it. So if you implemente the method on BaseAssetSearchTestCase we cover the two cases because we are extending this class on JournalAssetSearchTest (for translated results) and BlogsAssetSearchTest (for non translated results) 

We use BaseAssetSearchTestCase for everything related with assets, the test you added is regarding the results on Asset Publisher, so, I tend to think this is better to put it here.

For the code on BaseIndexer, Could we use the same map for adding the empty values instead of using a missingMap?

Regards,
Eudaldo.

**Comment by lipusz** [comment]
Got it. Thanks for the explanation!

One more thing: can you please test if you are able to run
````bash
ant test-class -Dtest.class=BlogsEntryAssetSearchTest
````

on today master? I get the stack below, and don't know how to proceed. ant test-integration doesn't work either

````bash
tibusz@tibusz-E6520:~/git/liferay-portal/portal-impl{master}$ ant test-class -Dtest.class=BlogsEntryAssetSearchTest
Buildfile: /home/tibusz/git/liferay-portal/portal-impl/build.xml

compile:

compile-dependencies:

check-compile-uptodate:

build-common-java.compile:

print-current-time:
     [echo] February 12, 2015 at 10:34 AM

test-class:
[ivy:resolve] :: Apache Ivy 2.3.0 - 20130110142753 :: http://ant.apache.org/ivy/ ::
[ivy:resolve] :: loading settings :: file = /home/tibusz/git/liferay-portal/ivy-settings.xml
    [mkdir] Created dir: /home/tibusz/git/liferay-portal/portal-impl/test-classes/integration
    [mkdir] Created dir: /home/tibusz/git/liferay-portal/portal-impl/test-results/integration
     [copy] Copying 565 files to /home/tibusz/git/liferay-portal/portal-impl/test-classes/integration
    [javac] Compiling 537 source files to /home/tibusz/git/liferay-portal/portal-impl/test-classes/integration
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.

check-compile-uptodate:

check-jar-uptodate:

compile:

jar:
    [junit] Loading jar:file:/home/tibusz/git/liferay-portal/portal-impl/portal-impl.jar!/system.properties
    [junit] Running com.liferay.portlet.blogs.asset.BlogsEntryAssetSearchTest
    [junit] Testsuite: com.liferay.portlet.blogs.asset.BlogsEntryAssetSearchTest
    [junit] Loading jar:file:/home/tibusz/git/liferay-portal/portal-impl/portal-impl.jar!/portal.properties
    [junit] Loading file:/home/tibusz/git/liferay-portal/portal-impl/test-classes/integration/portal-test.properties
    [junit] Loading file:/home/tibusz/git/liferay-portal/portal-impl/test-classes/integration/portal-test-ext.properties
    [junit] 09:34:47,198 ERROR [main][ModuleFrameworkAdapterHelper:67] Unable to configure the class loader for the module framework
    [junit] 09:34:47,201 ERROR [main][ModuleFrameworkAdapterHelper:81] Unable to load the module framework
    [junit] Tests run: 0, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.855 sec
    [junit] Tests run: 0, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.855 sec
    [junit] 
    [junit] Testcase: com.liferay.portlet.blogs.asset.BlogsEntryAssetSearchTest:	Caused an ERROR
    [junit] null
    [junit] java.lang.ExceptionInInitializerError
    [junit] 	at com.liferay.portal.util.InitUtil.initWithSpring(InitUtil.java:196)
    [junit] 	at com.liferay.portal.test.rule.LiferayIntegrationTestRule.apply(LiferayIntegrationTestRule.java:53)
    [junit] 	at com.liferay.portal.kernel.test.rule.AggregateTestRule.apply(AggregateTestRule.java:55)
    [junit] Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
    [junit] 	at com.liferay.portal.module.framework.ModuleFrameworkAdapterHelper.<init>(ModuleFrameworkAdapterHelper.java:83)
    [junit] 	at com.liferay.portal.module.framework.ModuleFrameworkUtilAdapter.<clinit>(ModuleFrameworkUtilAdapter.java:130)
    [junit] Caused by: java.lang.RuntimeException: java.lang.NullPointerException
    [junit] 	at com.liferay.portal.module.framework.ModuleFrameworkAdapterHelper.getClassLoader(ModuleFrameworkAdapterHelper.java:71)
    [junit] 	at com.liferay.portal.module.framework.ModuleFrameworkAdapterHelper.<init>(ModuleFrameworkAdapterHelper.java:77)
    [junit] Caused by: java.lang.NullPointerException
    [junit] 	at com.liferay.portal.module.framework.RuntimeClasspathResolver.getClasspathURLs(RuntimeClasspathResolver.java:34)
    [junit] 	at com.liferay.portal.module.framework.ModuleFrameworkAdapterHelper.getClassLoader(ModuleFrameworkAdapterHelper.java:59)
    [junit] 
    [junit] 
    [junit] Test com.liferay.portlet.blogs.asset.BlogsEntryAssetSearchTest FAILED

BUILD SUCCESSFUL
Total time: 14 seconds
tibusz@tibusz-E6520:~/git/liferay-portal/portal-impl{master}$
````

**Comment by lipusz** [comment]
I'll test the tests on 62x as a last hope.

**Comment by ealonso** [comment]
I test it on today master and it works for me.

```
    [junit] Tests run: 66, Failures: 0, Errors: 0, Skipped: 4, Time elapsed: 64,143 sec
    [junit] Tests run: 66, Failures: 0, Errors: 0, Skipped: 4, Time elapsed: 64,143 sec
    [junit] 
    [junit] Testcase: testClassTypeIds1(com.liferay.portlet.blogs.asset.BlogsEntryAssetSearchTest):SKIPPED
    [junit] Testcase: testClassTypeIds2(com.liferay.portlet.blogs.asset.BlogsEntryAssetSearchTest):SKIPPED
    [junit] Testcase: testOrderByExpirationDateAsc(com.liferay.portlet.blogs.asset.BlogsEntryAssetSearchTest):SKIPPED
    [junit] Testcase: testOrderByExpirationDateDesc(com.liferay.portlet.blogs.asset.BlogsEntryAssetSearchTest):SKIPPED
```

**Comment by lipusz** [comment]
Do you have anything "special" set in your portal-test-ext.properties?

**Comment by lipusz** [comment]
Weird... After setting

````properties
liferay.home=/home/tibusz/liferay/bundles/master
module.framework.base.dir=${liferay.home}/osgi
````

in portal-test-ext.properties,

I get

````bash
tibusz@tibusz-E6520:~/git/liferay-portal/portal-impl{LPS-53432-indexer-2}$ ant test-class -Dtest.class=BlogsEntrySearchTest
Buildfile: /home/tibusz/git/liferay-portal/portal-impl/build.xml

compile:

compile-dependencies:

check-compile-uptodate:

build-common-java.compile:

print-current-time:
     [echo] February 12, 2015 at 11:13 AM

test-class:
[ivy:resolve] :: Apache Ivy 2.3.0 - 20130110142753 :: http://ant.apache.org/ivy/ ::
[ivy:resolve] :: loading settings :: file = /home/tibusz/git/liferay-portal/ivy-settings.xml

check-compile-uptodate:

check-jar-uptodate:

compile:

jar:
    [junit] Loading jar:file:/home/tibusz/git/liferay-portal/portal-impl/portal-impl.jar!/system.properties
    [junit] Running com.liferay.portlet.blogs.search.BlogsEntrySearchTest
    [junit] Testsuite: com.liferay.portlet.blogs.search.BlogsEntrySearchTest
    [junit] Loading jar:file:/home/tibusz/git/liferay-portal/portal-impl/portal-impl.jar!/portal.properties
    [junit] Loading file:/home/tibusz/git/liferay-portal/portal-impl/test-classes/integration/portal-test.properties
    [junit] Loading file:/home/tibusz/git/liferay-portal/portal-impl/test-classes/integration/portal-test-ext.properties
    [junit] 10:13:46,018 INFO  [main][DialectDetector:71] Determine dialect for MySQL 5
    [junit] 10:13:46,041 INFO  [main][DialectDetector:136] Found dialect org.hibernate.dialect.MySQLDialect
    [junit] Testsuite: com.liferay.portlet.blogs.search.BlogsEntrySearchTest
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec
    [junit] 
    [junit] Testcase: com.liferay.portlet.blogs.search.BlogsEntrySearchTest:BeforeFirstTest:	Caused an ERROR
    [junit] Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] junit.framework.AssertionFailedError: Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] 	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
    [junit] 
    [junit] 
    [junit] Running com.liferay.portlet.blogs.search.BlogsEntrySearchTest
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec
    [junit] Test com.liferay.portlet.blogs.search.BlogsEntrySearchTest FAILED (crashed)

BUILD SUCCESSFUL
Total time: 27 seconds
tibusz@tibusz-E6520:~/git/liferay-portal/portal-impl{LPS-53432-indexer-2}$
````

I'm using JDK-1.7.0_75 64-bit + Ubuntu 14.10 64-bit.

What is you Java version?

**Comment by ealonso** [comment]
Nothing special

**Comment by lipusz** [comment]
git clean -fdx & re-building did the trick.

**Pull request closed without merging**
