### PR TITLE
LPS-76848 Buildlang

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54196. [See changes here.](https://github.com/ealonso/liferay-portal/compare/ec11222~4...ec11222) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54197. [See changes here.](https://github.com/ealonso/liferay-portal/compare/06cfcf5~5...06cfcf5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54199. [See changes here.](https://github.com/ealonso/liferay-portal/compare/7115b9b~5...7115b9b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
