### PR TITLE
[TECHNICAL-SUPPORT] LPS-94500

### PR DESCRIPTION
**Pull request by SamZiemer**

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/SamZiemer/liferay-portal/pull/585. [See changes here.](https://github.com/ealonso/liferay-portal/compare/8501c519ff67~2...8501c519ff67) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72294. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
