### PR TITLE
[TECHNICAL-SUPPORT] LPS-105343

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82139. [See changes here.](https://github.com/ealonso/liferay-portal/compare/0fc59f9ef81f~7...0fc59f9ef81f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
