### PR TITLE
[TS] LPS-94581

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-94581

CC @jrao 

The gist of the PR is when deleting a layout, we must also remove the data which customized pages hold onto in the portalPreferences table.  Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72471. [See changes here.](https://github.com/ealonso/liferay-portal/compare/ae4f13cae564~1...ae4f13cae564) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
