### PR TITLE
Ealonso pr 2632

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-104398

Hello @ealonso,

I looked through the changes and tested it in respect to non-staging, local staging, and remote staging. Everything is working as intended.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
@jonathanmccann, @ealonso is ooo until Monday, I sent the PR here: https://github.com/brianchandotcom/liferay-portal/pull/81631

From what I gather he already had reviewed it

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
